# Generated by Django 5.1.1 on 2025-03-17 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EnquriFromapi', '0002_initial'),
        ('itemmaster', '0001_initial'),
        ('itemmaster2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posotherincomecharges',
            name='other_income_charges_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.otherincomecharges'),
        ),
        migrations.AddField(
            model_name='productionorderfinishedgoods',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.category'),
        ),
        migrations.AddField(
            model_name='productionorderfinishedgoods',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_fg_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderfinishedgoods',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_fg_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderfinishedgoods',
            name='part_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='bom',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.bom'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_order_item_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_order_item_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='part_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.mrpsourcetype'),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_id_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='finished_goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionorderfinishedgoods'),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_id_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderlinkingtable',
            name='po_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionorderitem'),
        ),
        migrations.AddField(
            model_name='productionorderlinkingtable',
            name='po_item_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionorderitemdetail'),
        ),
        migrations.AddField(
            model_name='productionordermaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_master_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionordermaster',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.department'),
        ),
        migrations.AddField(
            model_name='productionordermaster',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_master_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderlinkingtable',
            name='po_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionordermaster'),
        ),
        migrations.AddField(
            model_name='materialrequestmaster',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionordermaster'),
        ),
        migrations.AddField(
            model_name='productionorderothercharges',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_other_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderothercharges',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_other_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='other_charges',
            field=models.ManyToManyField(blank=True, to='itemmaster.productionorderothercharges'),
        ),
        migrations.AddField(
            model_name='productionorderprocessroute',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_pr_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderprocessroute',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_pr_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='routes',
            field=models.ManyToManyField(blank=True, to='itemmaster.productionorderprocessroute'),
        ),
        migrations.AddField(
            model_name='productionorderrawmaterials',
            name='bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.bom'),
        ),
        migrations.AddField(
            model_name='productionorderrawmaterials',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.category'),
        ),
        migrations.AddField(
            model_name='productionorderrawmaterials',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_rm_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderrawmaterials',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_rm_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderrawmaterials',
            name='parent_bom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_bom', to='itemmaster.bom'),
        ),
        migrations.AddField(
            model_name='productionorderrawmaterials',
            name='part_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='raw_material',
            field=models.ManyToManyField(blank=True, to='itemmaster.productionorderrawmaterials'),
        ),
        migrations.AddField(
            model_name='materialrequestitemdetails',
            name='po_raw_material',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionorderrawmaterials'),
        ),
        migrations.AddField(
            model_name='productionorderscrap',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.category'),
        ),
        migrations.AddField(
            model_name='productionorderscrap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_scrap_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderscrap',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_scrap_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderscrap',
            name='part_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='scrap',
            field=models.ManyToManyField(blank=True, to='itemmaster.productionorderscrap'),
        ),
        migrations.AddField(
            model_name='productionordermaster',
            name='status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionorderstatus'),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionorderstatus'),
        ),
        migrations.AddField(
            model_name='materialrequestmaster',
            name='status',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionorderstatus'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.companyaddress'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.contactdetalis'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseOrder_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.department'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseOrder_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='other_expenses',
            field=models.ManyToManyField(blank=True, to='itemmaster.otherexpensespurchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_orders', to='itemmaster.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchaseOrder_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='purchase_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseOrderItem_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='hsn_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='item_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseOrderItem_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='item_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.purchaseorderitemdetails'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorderitemdetails'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallan_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallan_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='purchase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='purchase_return_challan_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallanItemDetails_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallanItemDetails_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='purchase_order_item_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorderitemdetails'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='purchase_return_challan_item_Details',
            field=models.ManyToManyField(blank=True, to='itemmaster.purchasereturnchallanitemdetails'),
        ),
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QualityInspectionReport_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QualityInspectionReport_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='qir_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qir', to='itemmaster.numberingserieslinking'),
        ),
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsreceiptnotestatus'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='quality_inspection_report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.qualityinspectionreport'),
        ),
        migrations.AddField(
            model_name='qualityinspectionsreportitemdetails',
            name='checked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityinspectionsreportitemdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QualityInspectionsReportItemDetails_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityinspectionsreportitemdetails',
            name='goods_receipt_note_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsreceiptnoteitemdetails'),
        ),
        migrations.AddField(
            model_name='qualityinspectionsreportitemdetails',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QualityInspectionsReportItemDetails_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='quality_inspections_report_item_detail_id',
            field=models.ManyToManyField(to='itemmaster.qualityinspectionsreportitemdetails'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rmcreate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Rmmodified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='part_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='bom',
            name='raw_material',
            field=models.ManyToManyField(blank=True, to='itemmaster.rawmaterial'),
        ),
        migrations.AddField(
            model_name='rawmaterialbomlink',
            name='bom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.bom'),
        ),
        migrations.AddField(
            model_name='rawmaterialbomlink',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.rawmaterial'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='createReportTemplate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifiedReportTemplate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='share_report',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepostype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createPOSTYPE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepostype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ModifiedPOSTYPE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='numberingseries',
            name='pos_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.resourcepostype'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReworkDeliveryChallan_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='dc_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RDC', to='itemmaster.numberingserieslinking'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReworkDeliveryChallan_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='purchase_order_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorder'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus'),
        ),
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='rework_delivery_challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.reworkdeliverychallan'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReworkDeliveryChallanItemDetails_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='hsn_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='item_master_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReworkDeliveryChallanItemDetails_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='purchaseOrderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorderitemdetails'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='rework_delivery_challan_item_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.reworkdeliverychallanitemdetails'),
        ),
        migrations.AddField(
            model_name='routing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routingScreate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routing',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routingmodified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderprocessroute',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.routing'),
        ),
        migrations.AddField(
            model_name='bomrouting',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.routing'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='BillingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BillingAddress', to='itemmaster.companyaddress'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='Currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencymaster'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='DeliverAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DeliverAddress', to='itemmaster.companyaddress'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='POS_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='SalesPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contactPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_contactPerson', to='itemmaster.contactdetalis'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='createpos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='marketingEvent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='EnquriFromapi.conferencedata'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifiedpos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='other_income_charge',
            field=models.ManyToManyField(blank=True, to='itemmaster.posotherincomecharges'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment',
            field=models.ManyToManyField(blank=True, to='itemmaster.paymentmode'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.pincode'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sample_contact_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sample_contact_link', to='itemmaster.contactdetalis'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.batchnumber'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_SalesOrderItem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_SalesOrderItem', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='part_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='itemDetails',
            field=models.ManyToManyField(blank=True, to='itemmaster.salesorderitem'),
        ),
        migrations.AddField(
            model_name='salesorderitemcombo',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.batchnumber'),
        ),
        migrations.AddField(
            model_name='salesorderitemcombo',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salesorderitemcombos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemcombo',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_salesorderitemcombos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemcombo',
            name='part_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='item_combo',
            field=models.ManyToManyField(blank=True, to='itemmaster.salesorderitemcombo'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Screate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrap',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Smodified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scrap',
            name='part_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='bom',
            name='scrap',
            field=models.ManyToManyField(blank=True, to='itemmaster.scrap'),
        ),
        migrations.AddField(
            model_name='salesorderitemcombo',
            name='serial',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='serial',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='serial_number',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
        migrations.AddField(
            model_name='iteminventoryapproval',
            name='serial_number',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='serial_number',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
        migrations.AddField(
            model_name='addressmaster',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.states'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster.itemstock'),
        ),
        migrations.AddField(
            model_name='stockhistorylog',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='stockhistorylog',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistorylog',
            name='stock_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster.itemstock'),
        ),
        migrations.AddField(
            model_name='stockserialhistory',
            name='part_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='store',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Store_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='store',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Store_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='store_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockserialhistory',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='stockhistorylog',
            name='store_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='store_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='receiving_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiving_store_ReworkDelivery_Challan', to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='scrap_reject_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrap_reject_store_ReworkDelivery_Challan', to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='receiving_store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receiving_store_id', to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='scrap_reject_store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scrap_reject_store_id', to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='productionorderscrap',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_scrap_store', to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='productionorderrawmaterials',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_rm_store', to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='materialrequestmaster',
            name='issuing_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='iteminventoryapproval',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='inventoryhandler',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='bom',
            name='fg_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FgStore', to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='bom',
            name='scrap_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ScrapRejectStore', to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='subproductionorders',
            name='bom_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.mrpsourcetype'),
        ),
        migrations.AddField(
            model_name='subproductionorders',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_po_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproductionorders',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_po_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproductionorders',
            name='part_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster'),
        ),
        migrations.AddField(
            model_name='subproductionorders',
            name='po_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionordermaster'),
        ),
        migrations.AddField(
            model_name='subproductionorders',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.productionorderstatus'),
        ),
        migrations.AddField(
            model_name='productionorderitemdetail',
            name='sub_production_orders',
            field=models.ManyToManyField(blank=True, to='itemmaster.subproductionorders'),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='address',
            field=models.ManyToManyField(to='itemmaster.companyaddress'),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='contact',
            field=models.ManyToManyField(to='itemmaster.contactdetalis'),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.customergroups'),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='gstin_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.gsttype'),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Supplier_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesPerson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='transport_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_id', to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='transport_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallan_transport_id', to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='mrpitem',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='supplier_data',
            field=models.ManyToManyField(blank=True, to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='bom',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='supplierformgsteffectivedate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_SupplierFormGstEffectiveDate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierformgsteffectivedate',
            name='gstin_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.gsttype'),
        ),
        migrations.AddField(
            model_name='supplierformgsteffectivedate',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_SupplierFormGstEffectiveDate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierformgsteffectivedate',
            name='supplier_form_data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='suppliergroups',
            name='Saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='supplier_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.suppliergroups'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Task_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Task_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TaskType_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TaskType_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.tasktype'),
        ),
        migrations.AddField(
            model_name='termsconditions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TermsConditions_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='termsconditions',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='termsconditions',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TermsConditions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions'),
        ),
        migrations.AddField(
            model_name='uom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createUOM', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uom',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='uom',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ModifiedUOM', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subproductionorders',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='salesorderitemcombo',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchaseOrderUnit', to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='productionorderscrap',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='productionorderrawmaterials',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='productionorderfinishedgoods',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='materialrequestitemdetails',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit', to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='purchase_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uom', to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='iteminventoryapproval',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='finishedgoods',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='alternate_unit',
            name='addtional_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UserGroupcreate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UserGroupmodified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='sub_group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.usergroup'),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorderprocessroute',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.workcenter'),
        ),
        migrations.AddField(
            model_name='bomrouting',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.workcenter'),
        ),
        migrations.AddConstraint(
            model_name='supplierformdata',
            constraint=models.UniqueConstraint(condition=models.Q(('pan_no__isnull', False)), fields=('pan_no',), name='unique_pan_no'),
        ),
        migrations.AlterUniqueTogether(
            name='uom',
            unique_together={('name',)},
        ),
    ]
