# Generated by Django 5.1.1 on 2025-03-25 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetalis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetalis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactDetalis_create', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactdetalis',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ContactDetalis_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactdetalis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
