# Generated by Django 5.1.1 on 2025-03-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0003_contactdetalis_created_at_contactdetalis_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierformdata',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
