# Generated by Django 5.1.1 on 2025-04-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0005_alter_numberingseries_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
