# Generated by Django 5.1.3 on 2025-04-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0006_alter_currencyexchange_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
