# Generated by Django 5.1.3 on 2025-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0007_alter_reporttemplate_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsn',
            name='description',
            field=models.TextField(),
        ),
    ]
