# Generated by Django 5.1.1 on 2025-05-19 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0008_alter_hsn_description'),
        ('userManagement', '0028_expenseclaim_history_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='modified_by',
        ),
        migrations.CreateModel(
            name='AccountsGeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('voucher_type', models.CharField(max_length=50)),
                ('debit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AccountsGeneralLedger_created', to=settings.AUTH_USER_MODEL)),
                ('customer_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee')),
                ('payment_voucher_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.paymentvoucher')),
            ],
            options={
                'verbose_name': 'General Ledger Entry',
                'verbose_name_plural': 'General Ledger Entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
