# Generated by Django 5.1.3 on 2025-05-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0010_alter_contactdetalis_salutation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetalis',
            name='salutation',
            field=models.CharField(blank=True, choices=[('MR', 'MR'), ('MS', 'MS'), ('MRS', 'MRS'), ('DR', 'DR'), ('M/S', 'M/S')], max_length=10, null=True),
        ),
    ]
