# Generated by Django 5.1.3 on 2025-05-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0009_remove_tasktype_created_by_and_more'),
        ('itemmaster', '0012_alter_contactdetalis_salutation'),
    ]

    operations = [
    ]
