# Generated by Django 5.1.1 on 2025-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0013_merge_20250523_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberingseries',
            name='resource',
            field=models.CharField(choices=[('Pos', 'Pos'), ('Purchase Order', 'Purchase Order'), ('Goods Inward Note', 'Goods Inward Note'), ('Goods Receipt Note', 'Goods Receipt Note'), ('Quality Inspection Report', 'Quality Inspection Report'), ('Rework Delivery Challan', 'Rework Delivery Challan'), ('Purchase Return Challan', 'Purchase Return Challan'), ('Quotations', 'Quotations'), ('SalesOrder', 'SalesOrder'), ('SalesOrder Delivery Challan', 'SalesOrder Delivery Challan'), ('Payment Voucher', 'Payment Voucher'), ('Target', 'Target')], max_length=50),
        ),
    ]
