# Generated by Django 5.1.1 on 2025-05-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0014_alter_numberingseries_resource'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplierformdata',
            name='unique_pan_no',
        ),
        migrations.AlterField(
            model_name='contactdetalis',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
