# Generated by Django 5.1.3 on 2025-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0014_alter_numberingseries_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsconditions',
            name='module',
            field=models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Sales', 'Sales'), ('Account', 'Account'), ('Service', 'Service'), ('Production', 'Production'), ('HR', 'HR'), ('Quotations', 'Quotations'), ('Sales_order', 'Sales_order'), ('SalesOrder Delivery Challan', 'SalesOrder Delivery Challan')], max_length=50),
        ),
    ]
