# Generated by Django 5.1.1 on 2025-05-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0015_alter_termsconditions_module'),
        ('itemmaster', '0015_remove_supplierformdata_unique_pan_no_and_more'),
    ]

    operations = [
    ]
