# Generated by Django 5.1.1 on 2025-05-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0016_merge_20250529_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
