# Generated by Django 5.1.1 on 2025-06-07 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0017_stockhistory_is_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryhandler',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_handler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryhandler',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus'),
        ),
        migrations.AddField(
            model_name='iteminventoryapproval',
            name='is_stock_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryhandler',
            name='saved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
