# Generated by Django 5.1.1 on 2025-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0018_inventoryhandler_modified_by_inventoryhandler_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberingseries',
            name='resource',
            field=models.CharField(choices=[('Pos', 'Pos'), ('Purchase Order', 'Purchase Order'), ('Goods Inward Note', 'Goods Inward Note'), ('Goods Receipt Note', 'Goods Receipt Note'), ('Quality Inspection Report', 'Quality Inspection Report'), ('Rework Delivery Challan', 'Rework Delivery Challan'), ('Purchase Return Challan', 'Purchase Return Challan'), ('Quotations', 'Quotations'), ('SalesOrder', 'SalesOrder'), ('SalesOrder Delivery Challan', 'SalesOrder Delivery Challan'), ('Payment Voucher', 'Payment Voucher'), ('Target', 'Target'), ('Sales Invoice', 'Sales Invoice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='termsconditions',
            name='module',
            field=models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Sales', 'Sales'), ('Account', 'Account'), ('Service', 'Service'), ('Production', 'Production'), ('HR', 'HR'), ('Quotations', 'Quotations'), ('Sales_order', 'Sales_order'), ('SalesOrder Delivery Challan', 'SalesOrder Delivery Challan'), ('Sales Invoice', 'Sales Invoice')], max_length=50),
        ),
    ]
