# Generated by Django 4.2.2 on 2025-06-23 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import itemmaster.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0019_alter_numberingseries_resource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, validators=[itemmaster.models.validate_phone])),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, validators=[itemmaster.models.validate_phone])),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True, validators=[itemmaster.models.validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('financial_year_start_from', models.DateField()),
                ('financial_year_end_from', models.DateField()),
                ('gst', models.BooleanField(default=False)),
                ('gst_state', models.CharField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('gstr1_filing_schedule', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20, null=True)),
                ('e_way_bill', models.BooleanField(default=False)),
                ('applicable_from', models.DateField(blank=True, null=True)),
                ('threshold_for_intrastate', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('threshold_for_interstate', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('tdc', models.BooleanField(default=False)),
                ('tds_tan_no', models.CharField(max_length=50)),
                ('deductor_type', models.CharField(blank=True, choices=[('company', 'Company'), ('individual/huf', 'Individual/huf')], max_length=20, null=True)),
                ('deductor_branch', models.CharField(max_length=50)),
                ('tsc', models.BooleanField(default=False)),
                ('tcs_tan_no', models.CharField(max_length=50)),
                ('collector_type', models.CharField(blank=True, choices=[('company', 'Company'), ('individual/huf', 'Individual/huf')], max_length=20, null=True)),
                ('collector_branch', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.addressmaster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_master_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencyexchange')),
                ('gst_in_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.gsttype')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_master_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
