# Generated by Django 4.2.2 on 2025-06-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0020_companymaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymaster',
            name='gst_state',
        ),
    ]
