# Generated by Django 5.1.3 on 2025-06-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0021_remove_companymaster_gst_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymaster',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.companyaddress'),
        ),
    ]
