# Generated by Django 4.2.2 on 2025-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0021_remove_companymaster_gst_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsn',
            name='taxability_type',
            field=models.CharField(blank=True, choices=[('taxable', 'Taxable'), ('nil rate', 'Nil Rate'), ('exempt', 'Exempt'), ('non-gst', 'Non-GST')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hsneffectivedate',
            name='taxability_type',
            field=models.CharField(blank=True, choices=[('taxable', 'Taxable'), ('nil rate', 'Nil Rate'), ('exempt', 'Exempt'), ('non-gst', 'Non-GST')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='gstr1_filing_schedule',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hsn',
            name='itc',
            field=models.BooleanField(default=False),
        ),
    ]
