# Generated by Django 4.2.2 on 2025-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0022_hsn_taxability_type_hsneffectivedate_taxability_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
