# Generated by Django 5.1.3 on 2025-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0022_alter_companymaster_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymaster',
            old_name='tdc',
            new_name='tcs',
        ),
        migrations.RenameField(
            model_name='companymaster',
            old_name='tsc',
            new_name='tds',
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='collector_branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='deductor_branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='tcs_tan_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymaster',
            name='tds_tan_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
