# Generated by Django 4.2.2 on 2025-06-25 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0023_alter_itemtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCSMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='TCS Name')),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_code', models.CharField(blank=True, max_length=50, null=True)),
                ('remittance_code', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_individual_with_pan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage for Individual/HUF with PAN')),
                ('percent_individual_without_pan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage for Individual/HUF without PAN')),
                ('percent_other_with_pan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage for Other with PAN')),
                ('percent_other_without_pan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage for Other without PAN')),
                ('zero_rated', models.BooleanField(default=False, verbose_name='Zero Rated')),
                ('tax_based_on_realization', models.BooleanField(default=False, verbose_name='Tax calculation based on realization')),
                ('exemption_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Exemption Limit')),
                ('single_transaction_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Single Transaction Limit')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TDSMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='TDS Name')),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_code', models.CharField(blank=True, max_length=50, null=True)),
                ('remittance_code', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_individual_with_pan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage for Individual/HUF with PAN')),
                ('percent_other_with_pan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage for Other with PAN')),
                ('zero_rated', models.BooleanField(default=False, verbose_name='Zero Rated')),
                ('exemption_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Exemption Limit')),
                ('single_transaction_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Single Transaction Limit')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='tcs_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.tcsmaster'),
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='tds_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.tdsmaster'),
        ),
    ]
