# Generated by Django 4.2.2 on 2025-06-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0023_rename_tdc_companymaster_tcs_and_more'),
        ('itemmaster', '0024_tcsmaster_tdsmaster_itemmaster_tcs_link_and_more'),
    ]

    operations = [
    ]
