# Generated by Django 4.2.2 on 2025-06-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0025_merge_20250625_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdsmaster',
            name='exemption_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Exemption Limit'),
        ),
        migrations.AlterField(
            model_name='tdsmaster',
            name='single_transaction_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Single Transaction Limit'),
        ),
    ]
