# Generated by Django 4.2.2 on 2025-06-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0026_alter_tdsmaster_exemption_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsmaster',
            name='tds',
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='gst_type',
            field=models.CharField(blank=True, choices=[('igst', 'Igst'), ('cgst', 'Cgst'), ('sgst', 'Sgst'), ('cess', 'Cess')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('gst', 'Gst'), ('tds', 'Tds'), ('tcs', 'Tcs'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='tcs_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.tcsmaster'),
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='tds_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.tdsmaster'),
        ),
        migrations.AlterField(
            model_name='tcsmaster',
            name='exemption_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Exemption Limit'),
        ),
        migrations.AlterField(
            model_name='tcsmaster',
            name='single_transaction_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Single Transaction Limit'),
        ),
    ]
