# Generated by Django 4.2.2 on 2025-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0027_remove_accountsmaster_tds_accountsmaster_gst_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsmaster',
            name='other_rate_tax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
