# Generated by Django 4.2.2 on 2025-06-26 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0028_accountsmaster_other_rate_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTNatureTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_transaction', models.CharField(max_length=255)),
                ('applies_to', models.CharField(choices=[('Sales', 'Sales'), ('Purchase', 'Purchase')], max_length=20)),
                ('gst_nature_type', models.CharField(choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify')], max_length=20)),
                ('specify_type', models.CharField(blank=True, choices=[('taxable', 'Taxable'), ('nil rate', 'Nil Rate'), ('exempt', 'Exempt'), ('non-gst', 'Non-GST')], max_length=20, null=True)),
                ('igst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cess_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GNT_create', to=settings.AUTH_USER_MODEL)),
                ('gstin_types', models.ManyToManyField(related_name='transactions', to='itemmaster.gsttype')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GNT_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
