# Generated by Django 4.2.2 on 2025-06-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0029_gstnaturetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaster',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencyexchange'),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplierformdata',
            name='tds',
            field=models.BooleanField(default=False),
        ),
    ]
