# Generated by Django 4.2.2 on 2025-06-26 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0030_companymaster_history_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TdsTcsEffectiveDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_individual_with_pan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage for Individual/HUF with PAN')),
                ('percent_individual_without_pan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage for Individual/HUF without PAN')),
                ('percent_other_with_pan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage for Other with PAN')),
                ('percent_other_without_pan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentage for Other without PAN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tcs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.tcsmaster')),
                ('tds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.tdsmaster')),
            ],
        ),
    ]
