# Generated by Django 4.2.2 on 2025-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0031_tdstcseffectivedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdstcseffectivedate',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='Effective Date'),
        ),
    ]
