# Generated by Django 4.2.2 on 2025-06-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0032_tdstcseffectivedate_effective_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstnaturetransaction',
            name='place_of_supply',
            field=models.CharField(blank=True, choices=[('Interstate', 'Interstate'), ('Intrastate', 'Intrastate')], max_length=20, null=True),
        ),
    ]
