# Generated by Django 5.1.3 on 2025-06-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0033_gstnaturetransaction_place_of_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstnaturetransaction',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
