# Generated by Django 4.2.2 on 2025-07-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0035_alter_gstnaturetransaction_specify_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcsmaster',
            name='percent_individual_without_pan',
        ),
    ]
