# Generated by Django 4.2.2 on 2025-07-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0036_remove_tcsmaster_percent_individual_without_pan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdstcseffectivedate',
            name='percent_individual_without_pan',
        ),
    ]
