# Generated by Django 4.2.2 on 2025-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0037_remove_tdstcseffectivedate_percent_individual_without_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstnaturetransaction',
            name='specify_type',
            field=models.CharField(blank=True, choices=[('taxable', 'Taxable'), ('nil rated', 'Nil Rated'), ('exempt', 'Exempt'), ('non-gst', 'Non-GST')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hsn',
            name='taxability_type',
            field=models.CharField(blank=True, choices=[('taxable', 'Taxable'), ('nil rated', 'Nil Rated'), ('exempt', 'Exempt'), ('non-gst', 'Non-GST')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hsneffectivedate',
            name='taxability_type',
            field=models.CharField(blank=True, choices=[('taxable', 'Taxable'), ('nil rated', 'Nil Rated'), ('exempt', 'Exempt'), ('non-gst', 'Non-GST')], max_length=20, null=True),
        ),
    ]
