# Generated by Django 4.2.2 on 2025-07-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0089_merge_20250717_1502'),
        ('userManagement', '0033_alter_allowedpermission_model_name'),
        ('itemmaster', '0038_alter_gstnaturetransaction_specify_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='sales_dc_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallan'),
        ),
        migrations.AlterField(
            model_name='accountsgeneralledger',
            name='payment_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.paymentvoucher'),
        ),
    ]
