# Generated by Django 4.2.2 on 2025-07-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0039_accountsgeneralledger_sales_dc_voucher_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsgeneralledger',
            options={'ordering': ['-id'], 'verbose_name': 'General Ledger Entry', 'verbose_name_plural': 'General Ledger Entries'},
        ),
    ]
