# Generated by Django 4.2.2 on 2025-07-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0091_remove_directsalesinvoice_sales_account_ledger_and_more'),
        ('itemmaster', '0040_alter_accountsgeneralledger_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='sales_invoice_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesinvoice'),
        ),
    ]
