# Generated by Django 4.2.2 on 2025-07-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0042_accountsgeneralledger_direct_sales_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaster',
            name='cess_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cess_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='cgst_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cgst_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='expense_advance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_advance_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='expense_reimbursement_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_reimbursement_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='forex_gain_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forex_gain_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='forex_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forex_loss_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='igst_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='igst_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='purchase_pending_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_pending_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='round_off_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='round_off_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='salary_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='salary_advance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salary_advance_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='sgst_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sgst_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='stock_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='stock_in_transit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_in_transit_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='tcs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tcs_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='tds_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tds_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='work_in_progress_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_in_progress_account', to='itemmaster.accountsmaster'),
        ),
    ]
