# Generated by Django 4.2.2 on 2025-07-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0043_companymaster_cess_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventoryapproval',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='iteminventoryapproval',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
