# Generated by Django 5.0.3 on 2025-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0044_iteminventoryapproval_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminventoryapproval',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='iteminventoryapproval',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
