# Generated by Django 4.2.2 on 2025-07-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0045_remove_iteminventoryapproval_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminventoryapproval',
            name='deletion_serial_number',
            field=models.ManyToManyField(to='itemmaster.serialnumbers'),
        ),
    ]
