# Generated by Django 4.2.2 on 2025-07-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0046_iteminventoryapproval_deletion_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemdetails',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemdetails',
            name='s_no',
        ),
        migrations.AddField(
            model_name='otherexpensespurchaseorder',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='cess',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='after_discount_value_for_per_item',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='round_off',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax_total',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
