# Generated by Django 4.2.2 on 2025-07-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0048_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpensespurchaseorder',
            name='after_discount_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otherexpensespurchaseorder',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otherexpensespurchaseorder',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='gin_links',
            field=models.ManyToManyField(blank=True, to='itemmaster.goodsreceiptnote'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='gst_nature_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.gstnaturetransaction'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify')], max_length=50, null=True),
        ),
    ]
