# Generated by Django 4.2.2 on 2025-07-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0049_otherexpensespurchaseorder_after_discount_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='gin_links',
        ),
        migrations.AlterField(
            model_name='iteminventoryapproval',
            name='deletion_serial_number',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
    ]
