# Generated by Django 4.2.2 on 2025-07-31 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0050_remove_purchaseorder_gin_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='gin_date',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='gin_no',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='GoodsInwardNoteItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qc', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GoodsInwardNoteItemDetails_create', to=settings.AUTH_USER_MODEL)),
                ('item_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GoodsInwardNoteItemDetails_modified', to=settings.AUTH_USER_MODEL)),
                ('purchase_order_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorderitemdetails')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInwardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gin_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Gin_create', to=settings.AUTH_USER_MODEL)),
                ('gin_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gin', to='itemmaster.numberingserieslinking')),
                ('goods_receipt_note_item_details_id', models.ManyToManyField(to='itemmaster.goodsinwardnoteitemdetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Gin_modified', to=settings.AUTH_USER_MODEL)),
                ('purchase_order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorder')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
            ],
        ),
    ]
