# Generated by Django 4.2.2 on 2025-08-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0051_remove_goodsreceiptnote_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnoteitemdetails',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnoteitemdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnoteitemdetails',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_order_id',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnoteitemdetails',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionreport',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionreport',
            name='qir_no',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionreport',
            name='quality_inspections_report_item_detail_id',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionreport',
            name='rework_delivery_challan',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionsreportitemdetails',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionsreportitemdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionsreportitemdetails',
            name='goods_receipt_note_item',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionsreportitemdetails',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='GoodsReceiptNote',
        ),
        migrations.DeleteModel(
            name='GoodsReceiptNoteItemDetails',
        ),
        migrations.DeleteModel(
            name='GoodsReceiptNoteStatus',
        ),
        migrations.DeleteModel(
            name='QualityInspectionReport',
        ),
        migrations.DeleteModel(
            name='QualityInspectionsReportItemDetails',
        ),
    ]
