# Generated by Django 4.2.2 on 2025-08-01 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0052_remove_goodsreceiptnoteitemdetails_batch_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspectionsReportItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rejected', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rework', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checked_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QualityInspectionsReportItemDetails_create', to=settings.AUTH_USER_MODEL)),
                ('goods_inward_note_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsinwardnoteitemdetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QualityInspectionsReportItemDetails_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qir_date', models.DateTimeField(null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QualityInspectionReport_create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='QualityInspectionReport_modified', to=settings.AUTH_USER_MODEL)),
                ('qir_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qir', to='itemmaster.numberingserieslinking')),
                ('quality_inspections_report_item_detail_id', models.ManyToManyField(to='itemmaster.qualityinspectionsreportitemdetails')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
            ],
        ),
    ]
