# Generated by Django 4.2.2 on 2025-08-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0055_alter_purchaseorder_parent_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinwardnote',
            name='gin_date',
            field=models.DateField(null=True),
        ),
    ]
