# Generated by Django 4.2.2 on 2025-08-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0057_purchaseorder_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinwardnote',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
