# Generated by Django 4.2.2 on 2025-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0058_goodsinwardnote_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinwardnote',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
