# Generated by Django 5.0.3 on 2025-08-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0059_goodsinwardnote_history_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='state',
        ),
    ]
