# Generated by Django 5.0.3 on 2025-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0060_remove_purchaseorder_country_and_more'),
        ('itemmaster2', '0095_alter_quotationsitemcomboitemdetails_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='email_record',
            field=models.ManyToManyField(blank=True, to='itemmaster2.emailrecord'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='note',
            field=models.ManyToManyField(blank=True, to='itemmaster2.notes'),
        ),
    ]
