# Generated by Django 4.2.2 on 2025-08-08 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0060_remove_purchaseorder_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptNoteItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockAdded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.batchnumber')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GoodsReceiptNoteItemDetails_create', to=settings.AUTH_USER_MODEL)),
                ('gin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsinwardnote')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GoodsReceiptNoteItemDetails_modified', to=settings.AUTH_USER_MODEL)),
                ('serial_number', models.ManyToManyField(blank=True, to='itemmaster.serialnumbers')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GRN_create', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt_note_item_details', models.ManyToManyField(to='itemmaster.goodsreceiptnoteitemdetails')),
                ('grn_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grn', to='itemmaster.numberingserieslinking')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='GRN_modified', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
            ],
        ),
    ]
