# Generated by Django 4.2.2 on 2025-08-08 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0061_goodsreceiptnoteitemdetails_goodsreceiptnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='goods_inward_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsinwardnote'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnoteitemdetails',
            name='gin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsinwardnoteitemdetails'),
        ),
    ]
