# Generated by Django 4.2.2 on 2025-08-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0062_goodsreceiptnote_goods_inward_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
