# Generated by Django 4.2.2 on 2025-08-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0063_goodsreceiptnoteitemdetails_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnoteitemdetails',
            name='batch_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnoteitemdetails',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
