# Generated by Django 4.2.2 on 2025-08-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0064_alter_goodsreceiptnoteitemdetails_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinwardnote',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsreceiptnote'),
        ),
    ]
