# Generated by Django 4.2.2 on 2025-08-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0065_goodsinwardnote_grn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsreceiptnoteitemdetails',
            old_name='stockAdded',
            new_name='stock_added',
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='all_stock_added',
            field=models.BooleanField(default=False),
        ),
    ]
