# Generated by Django 5.0.3 on 2025-08-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0061_purchaseorder_email_purchaseorder_email_record_and_more'),
        ('itemmaster', '0065_goodsinwardnote_grn'),
    ]

    operations = [
    ]
