# Generated by Django 5.0.3 on 2025-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0066_merge_20250809_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityinspectionreport',
            name='qir_date',
            field=models.DateField(null=True),
        ),
    ]
