# Generated by Django 4.2.2 on 2025-08-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0066_rename_stockadded_goodsreceiptnoteitemdetails_stock_added_and_more'),
        ('itemmaster', '0067_alter_qualityinspectionreport_qir_date'),
    ]

    operations = [
    ]
