# Generated by Django 4.2.2 on 2025-08-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0068_merge_20250811_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityinspectionsreportitemdetails',
            name='reject_last_serial',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualityinspectionsreportitemdetails',
            name='reject_stock_is_added',
            field=models.BooleanField(default=False),
        ),
    ]
