# Generated by Django 5.1.3 on 2025-08-12 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0069_qualityinspectionsreportitemdetails_reject_last_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinwardnote',
            name='quality_inspection_report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.qualityinspectionreport'),
        ),
    ]
