# Generated by Django 5.1.3 on 2025-08-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0070_alter_goodsinwardnote_quality_inspection_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
