# Generated by Django 5.1.3 on 2025-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0071_qualityinspectionreport_history_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityinspectionsreportitemdetails',
            name='reject_last_serial',
        ),
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='reject_last_serial',
            field=models.IntegerField(default=0),
        ),
    ]
