# Generated by Django 4.2.2 on 2025-08-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0072_remove_qualityinspectionsreportitemdetails_reject_last_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='grn_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
