# Generated by Django 4.2.2 on 2025-08-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0073_alter_goodsreceiptnote_grn_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='gin',
            field=models.ManyToManyField(blank=True, to='itemmaster.goodsinwardnote'),
        ),
    ]
