# Generated by Django 5.1.3 on 2025-08-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0074_purchaseorder_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
