# Generated by Django 4.2.2 on 2025-08-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0074_purchaseorder_gin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinwardnote',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.goodsreceiptnote'),
        ),
    ]
