# Generated by Django 4.2.2 on 2025-08-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0075_alter_goodsinwardnote_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
