# Generated by Django 4.2.2 on 2025-08-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0075_goodsreceiptnote_history_details'),
        ('itemmaster', '0076_purchaseorderitemdetails_conversion_rate'),
    ]

    operations = [
    ]
