# Generated by Django 4.2.2 on 2025-08-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0077_merge_20250816_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitemdetails',
            name='conversion_rate',
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='conversion_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
