# Generated by Django 4.2.2 on 2025-08-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0078_remove_purchaseorderitemdetails_conversion_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturnchallan',
            old_name='purchase_id',
            new_name='purchase',
        ),
        migrations.RenameField(
            model_name='purchasereturnchallan',
            old_name='transport_id',
            new_name='transport',
        ),
        migrations.RenameField(
            model_name='reworkdeliverychallanitemdetails',
            old_name='purchaseOrderItem',
            new_name='purchase_orderItem',
        ),
        migrations.RemoveField(
            model_name='purchasereturnchallan',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='purchasereturnchallan',
            name='own_vehicle',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='receiving_store',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='scrap_reject_store',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallanitemdetails',
            name='hsn_id',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallanitemdetails',
            name='in_ward_reduce',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallanitemdetails',
            name='item_master_id',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallanitemdetails',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallanitemdetails',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallanitemdetails',
            name='uom',
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='docket_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='docket_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='driver_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # migrations.AlterField(
        #     model_name='reworkdeliverychallan',
        #     name='address',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.companyaddress'),
        # ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='address',
        ),
    ]
