# Generated by Django 4.2.2 on 2025-08-18 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0079_rename_purchase_id_purchasereturnchallan_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.companyaddress'),
        ),
    ]
