# Generated by Django 4.2.2 on 2025-08-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0080_reworkdeliverychallan_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reworkdeliverychallan',
            old_name='transport_id',
            new_name='transport',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='own_vehicle',
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='docket_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='docket_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='driver_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
