# Generated by Django 4.2.2 on 2025-08-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0081_rename_transport_id_reworkdeliverychallan_transport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='gstin_type',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='state',
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.qualityinspectionreport'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='qc_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.qualityinspectionsreportitemdetails'),
        ),
    ]
