# Generated by Django 4.2.2 on 2025-08-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0082_remove_reworkdeliverychallan_gstin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitemdetails',
            old_name='purchase_retun_qty',
            new_name='rework_received',
        ),
        migrations.RemoveField(
            model_name='purchasereturnchallan',
            name='qc',
        ),
        migrations.RemoveField(
            model_name='purchasereturnchallanitemdetails',
            name='qc_item',
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='rework_retun_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='qualityinspectionreport',
            name='rework_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.reworkdeliverychallan'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.qualityinspectionreport'),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='qc_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.qualityinspectionsreportitemdetails'),
        ),
    ]
