# Generated by Django 4.2.2 on 2025-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0083_rename_purchase_retun_qty_purchaseorderitemdetails_rework_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='inward_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='rework_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
    ]
