# Generated by Django 4.2.2 on 2025-08-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0084_reworkdeliverychallan_inward_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='inward_percentage',
        ),
        migrations.RemoveField(
            model_name='reworkdeliverychallan',
            name='rework_percentage',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='inward_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='rework_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
    ]
