# Generated by Django 4.2.2 on 2025-08-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0085_remove_reworkdeliverychallan_inward_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='received_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reworkdeliverychallanitemdetails',
            name='rework_qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
