# Generated by Django 4.2.2 on 2025-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0086_reworkdeliverychallanitemdetails_received_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='inward_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='rework_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
