# Generated by Django 4.2.2 on 2025-08-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0087_alter_purchaseorder_inward_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
