# Generated by Django 4.2.2 on 2025-08-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0089_otherexpensespurchaseorder_cess_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='purchase_invoice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
