# Generated by Django 4.2.2 on 2025-08-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0090_reworkdeliverychallanitemdetails_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_invoice_submit_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='otherexpensespurchaseorder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_income_charges', to='itemmaster.otherexpensespurchaseorder'),
        ),
    ]
