# Generated by Django 4.2.2 on 2025-08-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0091_goodsreceiptnoteitemdetails_purchase_invoice_submit_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.purchaseinvoice'),
        ),
    ]
