# Generated by Django 4.2.2 on 2025-08-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0092_goodsreceiptnote_purchase_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitemdetails',
            name='grn_item',
            field=models.ManyToManyField(to='itemmaster.goodsreceiptnoteitemdetails'),
        ),
    ]
