# Generated by Django 5.0.3 on 2025-08-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0092_goodsreceiptnote_purchase_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsconditions',
            name='module',
            field=models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Sales', 'Sales'), ('Account', 'Account'), ('Service', 'Service'), ('Production', 'Production'), ('HR', 'HR'), ('Quotations', 'Quotations'), ('Sales_order', 'Sales_order'), ('SalesOrder Delivery Challan', 'SalesOrder Delivery Challan'), ('Sales Invoice', 'Sales Invoice'), ('Rework Dc', 'Rework Dc')], max_length=50),
        ),
    ]
