# Generated by Django 4.2.2 on 2025-08-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0093_alter_purchaseinvoiceitemdetails_grn_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='is_draft_in_purchase_invoice_qty',
            field=models.BooleanField(default=False),
        ),
    ]
