# Generated by Django 4.2.2 on 2025-08-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0094_goodsreceiptnoteitemdetails_is_draft_in_purchase_invoice_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsreceiptnoteitemdetails',
            old_name='is_draft_in_purchase_invoice_qty',
            new_name='is_draft_purchase_invoice',
        ),
        migrations.RemoveField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_invoice_submit_qty',
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='is_submited_purchase_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
