# Generated by Django 4.2.2 on 2025-08-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0095_rename_is_draft_in_purchase_invoice_qty_goodsreceiptnoteitemdetails_is_draft_purchase_invoice_and_mo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reworkdeliverychallanitemdetails',
            name='purchase_orderItem',
        ),
    ]
