# Generated by Django 4.2.2 on 2025-08-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0094_alter_termsconditions_module'),
        ('itemmaster', '0096_remove_reworkdeliverychallanitemdetails_purchase_orderitem'),
    ]

    operations = [
    ]
