# Generated by Django 4.2.2 on 2025-08-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0097_merge_20250826_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='gstin',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='gstin_type',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier_ref',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='credit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
