# Generated by Django 4.2.2 on 2025-08-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0098_remove_purchaseinvoice_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnote',
            name='purchase_invoice',
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='purchase_invoice',
            field=models.ManyToManyField(blank=True, to='itemmaster.purchaseinvoice'),
        ),
    ]
