# Generated by Django 4.2.2 on 2025-08-26 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0099_remove_goodsreceiptnote_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkdeliverychallanitemdetails',
            name='purchase_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorderitemdetails'),
        ),
    ]
