# Generated by Django 4.2.2 on 2025-08-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0100_reworkdeliverychallanitemdetails_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='e_way_bill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='e_way_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
