# Generated by Django 4.2.2 on 2025-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0101_reworkdeliverychallan_e_way_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='e_way_bill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='e_way_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
