# Generated by Django 4.2.2 on 2025-08-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0102_goodsreceiptnote_e_way_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinwardnote',
            name='rework_delivery_challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.reworkdeliverychallan'),
        ),
        migrations.AddField(
            model_name='goodsinwardnoteitemdetails',
            name='reword_delivery_challan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.reworkdeliverychallanitemdetails'),
        ),
    ]
