# Generated by Django 4.2.2 on 2025-08-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0103_goodsinwardnote_rework_delivery_challan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='rework_percentage',
        ),
    ]
