# Generated by Django 4.2.2 on 2025-08-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0104_remove_purchaseorder_rework_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='rework_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
