# Generated by Django 5.0.3 on 2025-08-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0106_alter_termsconditions_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='e_way_bill',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='e_way_bill_date',
        ),
    ]
