# Generated by Django 4.2.2 on 2025-08-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0107_remove_purchaseinvoice_e_way_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturnchallanitemdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchasereturnchallanitemdetails',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='purchasereturnchallanitemdetails',
            name='purchase_order_item_details',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='address',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='terms_conditions_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseReturnChallan',
        ),
        migrations.DeleteModel(
            name='PurchaseReturnChallanItemDetails',
        ),
    ]
