# Generated by Django 4.2.2 on 2025-08-29 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster', '0108_remove_purchasereturnchallanitemdetails_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRetunBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsreceiptnoteitemdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnChallanItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retun_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ManyToManyField(blank=True, to='itemmaster.purchaseretunbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallanItemDetails_create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallanItemDetails_modified', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseinvoiceitemdetails')),
                ('serial', models.ManyToManyField(blank=True, to='itemmaster.serialnumbers')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_return_date', models.DateField()),
                ('eway_bill_no', models.CharField(blank=True, max_length=50, null=True)),
                ('eway_bill_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('terms_conditions_text', models.TextField()),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=20, null=True)),
                ('docket_no', models.CharField(blank=True, max_length=30, null=True)),
                ('docket_date', models.DateField(blank=True, null=True)),
                ('other_model', models.TextField(blank=True, null=True)),
                ('igst', models.JSONField(blank=True, null=True)),
                ('sgst', models.JSONField(blank=True, null=True)),
                ('cgst', models.JSONField(blank=True, null=True)),
                ('cess', models.JSONField(blank=True, null=True)),
                ('befor_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('round_off', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallan_create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallan_modified', to=settings.AUTH_USER_MODEL)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseinvoice')),
                ('purchase_return_challan_item_Details', models.ManyToManyField(to='itemmaster.purchasereturnchallanitemdetails')),
                ('purchase_return_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
                ('terms_conditions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PurchaseReturnChallan_transport_id', to='itemmaster.supplierformdata')),
            ],
        ),
    ]
