# Generated by Django 5.2.5 on 2025-09-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0109_purchaseretunbatch_purchasereturnchallanitemdetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturnchallan',
            name='purchase_invoice',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_retun',
            field=models.ManyToManyField(blank=True, to='itemmaster.purchasereturnchallan'),
        ),
    ]
