# Generated by Django 5.2.5 on 2025-09-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0110_remove_purchasereturnchallan_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='grn',
            field=models.ManyToManyField(to='itemmaster.goodsreceiptnoteitemdetails'),
        ),
    ]
