# Generated by Django 5.2.5 on 2025-09-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0111_purchasereturnchallanitemdetails_grn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturnchallanitemdetails',
            old_name='grn',
            new_name='grn_item',
        ),
    ]
