# Generated by Django 5.2.5 on 2025-09-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0112_rename_grn_purchasereturnchallanitemdetails_grn_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='purchase_retun',
            field=models.ManyToManyField(blank=True, to='itemmaster.purchasereturnchallan'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_return_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
