# Generated by Django 4.2.2 on 2025-09-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0113_goodsreceiptnote_purchase_retun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_invoice_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
