# Generated by Django 5.0.3 on 2025-09-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0110_alter_termsconditions_module'),
        ('itemmaster', '0114_goodsreceiptnoteitemdetails_purchase_invoice_qty'),
    ]

    operations = [
    ]
