# Generated by Django 5.2.5 on 2025-09-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0115_merge_20250903_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturnchallanitemdetails',
            old_name='retun_qty',
            new_name='return_qty',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='purchase_retun',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_retun',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.purchasereturnchallan'),
        ),
    ]
