# Generated by Django 5.2.5 on 2025-09-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0115_merge_20250904_1308'),
        ('itemmaster', '0116_rename_retun_qty_purchasereturnchallanitemdetails_return_qty_and_more'),
    ]

    operations = [
    ]
