# Generated by Django 5.0.3 on 2025-09-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0117_merge_20250904_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturnchallanitemdetails',
            name='grn_item',
            field=models.ManyToManyField(blank=True, to='itemmaster.goodsreceiptnoteitemdetails'),
        ),
        migrations.AlterField(
            model_name='purchasereturnchallanitemdetails',
            name='purchase_invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseinvoiceitemdetails'),
        ),
    ]
