# Generated by Django 5.0.3 on 2025-09-05 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0118_alter_purchasereturnchallanitemdetails_grn_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturnchallan',
            name='purchase_return_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
    ]
