# Generated by Django 5.2.5 on 2025-09-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0119_alter_purchasereturnchallan_purchase_return_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseretunbatch',
            name='is_stock_reduce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='is_stock_reduce',
            field=models.BooleanField(default=False),
        ),
    ]
