# Generated by Django 5.0.3 on 2025-09-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0119_alter_purchasereturnchallan_purchase_return_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencymaster',
            name='formate',
        ),
        migrations.DeleteModel(
            name='CurrencyFormate',
        ),
    ]
