# Generated by Django 5.2.5 on 2025-09-09 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0120_purchaseretunbatch_is_stock_reduce_and_more'),
        ('itemmaster', '0120_remove_currencymaster_formate_delete_currencyformate'),
    ]

    operations = [
    ]
