# Generated by Django 5.2.5 on 2025-09-09 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0121_merge_20250909_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRetunNobatchNoserial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('is_stock_reduce', models.BooleanField(default=False)),
                ('nobatch_noserial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsreceiptnoteitemdetails')),
            ],
        ),
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='nobatch_noserial',
            field=models.ManyToManyField(blank=True, to='itemmaster.purchaseretunnobatchnoserial'),
        ),
    ]
