# Generated by Django 5.2.5 on 2025-09-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0122_purchaseretunnobatchnoserial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
