# Generated by Django 5.0.3 on 2025-09-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0125_alter_numberingseries_resource_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directpurchaseinvoice',
            name='customer_po',
        ),
        migrations.RemoveField(
            model_name='directpurchaseinvoice',
            name='customer_po_date',
        ),
        migrations.RemoveField(
            model_name='directpurchaseinvoice',
            name='sales_person',
        ),
    ]
