# Generated by Django 5.0.3 on 2025-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0126_remove_directpurchaseinvoice_customer_po_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpurchaseinvoice',
            name='other_expence_charge',
            field=models.ManyToManyField(blank=True, to='itemmaster.otherexpensespurchaseorder'),
        ),
    ]
