# Generated by Django 5.0.3 on 2025-09-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0127_directpurchaseinvoice_other_expence_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpurchaseinvoice',
            name='creadit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
