# Generated by Django 5.2.5 on 2025-09-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0127_directpurchaseinvoice_other_expence_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherexpensespurchaseorder',
            name='after_discount_value',
        ),
        migrations.RemoveField(
            model_name='otherexpensespurchaseorder',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='discount_final_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='overall_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='overall_discount_value',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemdetails',
            name='after_discount_value_for_per_item',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemdetails',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemdetails',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemdetails',
            name='final_value',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitemdetails',
            name='verified_amount',
        ),
        migrations.AddField(
            model_name='alternate_unit',
            name='variation',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='po_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='po_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='po_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_uom', to='itemmaster.uom'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitemdetails',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_uom', to='itemmaster.uom'),
        ),
    ]
