# Generated by Django 5.2.5 on 2025-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0128_remove_otherexpensespurchaseorder_after_discount_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptnoteitemdetails',
            name='conversion_qty',
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='alternate_unit',
            name='variation',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_invoice_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_return_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnoteitemdetails',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
