# Generated by Django 5.0.3 on 2025-09-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0128_directpurchaseinvoice_creadit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpurchaseinvoice',
            name='supplier_ref',
            field=models.TextField(blank=True, null=True),
        ),
    ]
