# Generated by Django 5.2.5 on 2025-09-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0129_remove_goodsreceiptnoteitemdetails_conversion_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoiceitemdetails',
            old_name='after_discount_value_for_per_item',
            new_name='billing_qty',
        ),
        migrations.RenameField(
            model_name='purchaseinvoiceitemdetails',
            old_name='discount_percentage',
            new_name='billing_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='discount_final_total',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='overall_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='overall_discount_value',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitemdetails',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitemdetails',
            name='final_value',
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitemdetails',
            name='billing_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitemdetails',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='billed_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnchallanitemdetails',
            name='billed_return_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gstnaturetransaction',
            name='gst_nature_type',
            field=models.CharField(choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify'), ('import Purchase', 'import Purchase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturnchallanitemdetails',
            name='return_qty',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
