# Generated by Django 5.0.3 on 2025-09-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0129_directpurchaseinvoice_supplier_ref'),
        ('itemmaster', '0129_remove_goodsreceiptnoteitemdetails_conversion_qty_and_more'),
    ]

    operations = [
    ]
