# Generated by Django 5.0.3 on 2025-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0130_merge_20250915_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitemdetails',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
