# Generated by Django 5.2.5 on 2025-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0130_rename_after_discount_value_for_per_item_purchaseinvoiceitemdetails_billing_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstnaturetransaction',
            name='gst_nature_type',
            field=models.CharField(choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify'), ('Import Purchase', 'Import Purchase')], max_length=20),
        ),
    ]
