# Generated by Django 5.0.3 on 2025-09-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0131_alter_purchaseorderitemdetails_conversion_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternate_unit',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=5, max_digits=11),
        ),
    ]
