# Generated by Django 5.0.3 on 2025-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0132_alter_alternate_unit_conversion_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
