# Generated by Django 5.0.3 on 2025-09-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0131_alter_gstnaturetransaction_gst_nature_type'),
        ('itemmaster', '0133_purchaseorderitemdetails_fixed'),
    ]

    operations = [
    ]
