# Generated by Django 5.0.3 on 2025-09-17 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0134_merge_20250917_1334'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('company_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.companymaster')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_detail_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_detail_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Detail',
                'verbose_name_plural': 'Bank Details',
                'db_table': 'bank_details',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_entry_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_of_entry_date', models.DateField(blank=True, null=True)),
                ('port_code', models.CharField(blank=True, max_length=10, null=True)),
                ('total_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='itemmaster.purchaseinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessable_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('import_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='itemmaster.purchaseinvoiceimport')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseinvoiceitemdetails')),
            ],
        ),
    ]
