# Generated by Django 5.0.3 on 2025-09-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0135_bankdetails_purchaseinvoiceimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptnoteitemdetails',
            name='base_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
