# Generated by Django 5.2.5 on 2025-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0136_goodsreceiptnoteitemdetails_base_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoiceitemdetails',
            old_name='amount',
            new_name='po_amount',
        ),
        migrations.RenameField(
            model_name='purchaseinvoiceitemdetails',
            old_name='qty',
            new_name='po_qty',
        ),
        migrations.RenameField(
            model_name='purchaseinvoiceitemdetails',
            old_name='rate',
            new_name='po_rate',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitemdetails',
            name='billing_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitemdetails',
            name='billing_qty',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitemdetails',
            name='billing_rate',
        ),
        migrations.AlterField(
            model_name='directpurchaseinvoice',
            name='gst_nature_type',
            field=models.CharField(choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify'), ('Import Purchase', 'Import Purchase')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify'), ('Import Purchase', 'Import Purchase')], max_length=50, null=True),
        ),
    ]
