# Generated by Django 5.2.5 on 2025-09-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0137_rename_amount_purchaseinvoiceitemdetails_po_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceimportline',
            name='assessable_hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
    ]
