# Generated by Django 5.2.5 on 2025-09-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0138_purchaseinvoiceimportline_assessable_hsn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasereturnchallanitemdetails',
            old_name='billed_return_qty',
            new_name='base_return_qty',
        ),
        migrations.RenameField(
            model_name='purchasereturnchallanitemdetails',
            old_name='amount',
            new_name='po_amount',
        ),
        migrations.RenameField(
            model_name='purchasereturnchallanitemdetails',
            old_name='return_qty',
            new_name='po_return_qty',
        ),
        migrations.RemoveField(
            model_name='purchasereturnchallanitemdetails',
            name='billed_amount',
        ),
    ]
