# Generated by Django 5.2.5 on 2025-09-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0140_alter_termsconditions_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternate_unit',
            name='variation',
        ),
        migrations.AlterField(
            model_name='alternate_unit',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
