# Generated by Django 5.2.5 on 2025-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0141_remove_alternate_unit_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternate_unit',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
