# Generated by Django 5.0.3 on 2025-10-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0142_alter_alternate_unit_conversion_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherexpensespurchaseorder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_income_charges', to='itemmaster.otherexpensespurchaseorder'),
        ),
    ]
