# Generated by Django 5.2.5 on 2025-10-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0143_debitnote_debitnoteitemdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteitemdetail',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='debitnoteitemdetail',
            name='po_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='debit_note_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
        migrations.AlterField(
            model_name='otherexpensespurchaseorder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_income_charges', to='itemmaster.otherexpensespurchaseorder'),
        ),
    ]
