# Generated by Django 5.2.5 on 2025-10-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0144_debitnoteitemdetail_conversion_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityinspectionsreportitemdetails',
            name='accepted',
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
        migrations.AlterField(
            model_name='qualityinspectionsreportitemdetails',
            name='rejected',
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
        migrations.AlterField(
            model_name='qualityinspectionsreportitemdetails',
            name='rework',
            field=models.DecimalField(decimal_places=4, max_digits=11),
        ),
    ]
