# Generated by Django 5.2.5 on 2025-10-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0145_alter_qualityinspectionsreportitemdetails_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityinspectionreport',
            name='rework_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.reworkdeliverychallan'),
        ),
    ]
