# Generated by Django 5.0.3 on 2025-10-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0143_alter_otherexpensespurchaseorder_parent'),
        ('itemmaster', '0146_alter_qualityinspectionreport_rework_received'),
    ]

    operations = [
    ]
