# Generated by Django 5.0.3 on 2025-10-14 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0148_alter_numberingseries_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteitemdetail',
            name='debit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.debitnote'),
        ),
    ]
