# Generated by Django 5.0.3 on 2025-10-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0149_alter_debitnoteitemdetail_debit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteotherincomecharge',
            name='debit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.debitnote'),
        ),
    ]
