# Generated by Django 5.0.3 on 2025-10-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0150_alter_debitnoteotherincomecharge_debit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsconditions',
            name='module',
            field=models.CharField(choices=[('Purchase Order', 'Purchase Order'), ('Sales', 'Sales'), ('Account', 'Account'), ('Service', 'Service'), ('Production', 'Production'), ('HR', 'HR'), ('Quotations', 'Quotations'), ('Sales_order', 'Sales_order'), ('SalesOrder Delivery Challan', 'SalesOrder Delivery Challan'), ('Sales Invoice', 'Sales Invoice'), ('Rework DC', 'Rework DC'), ('Purchase Invoice', 'Purchase Invoice'), ('Purchase Return', 'Purchase Return')], max_length=50),
        ),
    ]
