# Generated by Django 5.0.3 on 2025-10-14 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0151_alter_termsconditions_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteitemdetail',
            name='debit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.debitnote'),
        ),
        migrations.AlterField(
            model_name='debitnoteotherincomecharge',
            name='debit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.debitnote'),
        ),
    ]
