# Generated by Django 5.0.3 on 2025-10-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0152_alter_debitnoteitemdetail_debit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='note_no',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
