# Generated by Django 5.2.5 on 2025-10-16 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0153_debitnote_note_date_debitnote_note_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNoteAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cess', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tds_percentage', models.IntegerField(blank=True, null=True)),
                ('tcs_percentage', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster')),
                ('debit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.debitnote')),
                ('hsn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn')),
            ],
        ),
    ]
