# Generated by Django 5.2.5 on 2025-10-16 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0154_debitnoteaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debitnoteaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_debit_note_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnoteaccount',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_debit_note_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debitnoteaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
