# Generated by Django 5.2.5 on 2025-10-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0155_debitnoteaccount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteitemdetail',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
