# Generated by Django 5.2.5 on 2025-10-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0156_debitnoteitemdetail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteaccount',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='debitnoteitemdetail',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
