# Generated by Django 5.2.5 on 2025-10-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0157_debitnoteaccount_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteaccount',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnoteitemdetail',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
