# Generated by Django 5.0.3 on 2025-10-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0158_debitnoteaccount_index_debitnoteitemdetail_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteitemdetail',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='debitnoteitemdetail',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_base_uom', to='itemmaster.uom'),
        ),
    ]
