# Generated by Django 5.2.5 on 2025-10-17 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0158_debitnoteaccount_index_debitnoteitemdetail_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directpurchaseinvoiceitemdetails',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DirectPurchaseInvoiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cess', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('igst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cess_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tds_percentage', models.IntegerField(blank=True, null=True)),
                ('tcs_percentage', models.IntegerField(blank=True, null=True)),
                ('tds_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tcs_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_direct_purchase_invoice_account', to=settings.AUTH_USER_MODEL)),
                ('direct_purchase_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.directpurchaseinvoice')),
                ('hsn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_direct_purchase_invoice_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
