# Generated by Django 5.0.3 on 2025-10-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0159_alter_debitnoteitemdetail_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteaccount',
            name='tcs_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='debitnoteaccount',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
