# Generated by Django 5.0.3 on 2025-10-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0160_alter_debitnoteaccount_tcs_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteitemdetail',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
