# Generated by Django 5.2.5 on 2025-10-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0159_directpurchaseinvoiceitemdetails_index_and_more'),
        ('itemmaster', '0161_alter_debitnoteitemdetail_amount'),
    ]

    operations = [
    ]
