# Generated by Django 5.0.3 on 2025-10-18 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0159_directpurchaseinvoiceitemdetails_index_and_more'),
        ('itemmaster', '0161_alter_debitnoteitemdetail_amount'),
    ]

    operations = [
    ]
