# Generated by Django 5.2.5 on 2025-10-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0162_merge_20251022_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitemdetails',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorderitemdetails'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='invoice_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitemdetails',
            name='invoiced_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitemdetails',
            name='grn_item',
            field=models.ManyToManyField(blank=True, to='itemmaster.goodsreceiptnoteitemdetails'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='inward_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
