# Generated by Django 5.0.3 on 2025-10-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0162_merge_20251018_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnoteaccount',
            name='hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
        migrations.AlterField(
            model_name='directpurchaseinvoiceaccount',
            name='hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
        migrations.AlterField(
            model_name='directpurchaseinvoiceaccount',
            name='tcs_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='directpurchaseinvoiceaccount',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
