# Generated by Django 5.0.3 on 2025-10-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0163_alter_debitnoteaccount_hsn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpensespurchaseorder',
            name='hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
    ]
