# Generated by Django 5.2.5 on 2025-10-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0163_purchaseinvoiceitemdetails_po_item_and_more'),
        ('itemmaster', '0164_otherexpensespurchaseorder_hsn'),
    ]

    operations = [
    ]
