# Generated by Django 5.0.3 on 2025-10-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0163_purchaseinvoiceitemdetails_po_item_and_more'),
        ('itemmaster', '0164_otherexpensespurchaseorder_hsn'),
    ]

    operations = [
    ]
