# Generated by Django 5.0.3 on 2025-10-23 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0165_merge_20251023_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseorder'),
        ),
    ]
