# Generated by Django 5.2.5 on 2025-10-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0165_merge_20251022_1854'),
        ('itemmaster', '0166_purchasereturnchallan_purchase_order'),
    ]

    operations = [
    ]
