# Generated by Django 5.2.5 on 2025-10-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0167_merge_20251023_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='goods_receipt_note_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.goodsreceiptnote'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
    ]
