# Generated by Django 5.2.5 on 2025-10-25 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0168_accountsgeneralledger_goods_receipt_note_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseinvoice'),
        ),
    ]
