# Generated by Django 5.2.5 on 2025-10-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0169_accountsgeneralledger_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
    ]
