# Generated by Django 5.2.5 on 2025-10-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0170_purchaseinvoice_is_account_general_ledger_upated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceimportline',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster.purchaseinvoiceitemdetails'),
        ),
    ]
