# Generated by Django 5.2.5 on 2025-10-25 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0171_alter_purchaseinvoiceimportline_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='direct_purchase_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.directpurchaseinvoice'),
        ),
        migrations.AddField(
            model_name='directpurchaseinvoice',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
    ]
