# Generated by Django 5.2.5 on 2025-10-27 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0172_accountsgeneralledger_direct_purchase_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='purchase_return_challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchasereturnchallan'),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
    ]
