# Generated by Django 5.2.5 on 2025-10-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0173_accountsgeneralledger_purchase_return_challan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsgeneralledger',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='accountsgeneralledger',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
