# Generated by Django 5.0.3 on 2025-10-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0173_accountsgeneralledger_purchase_return_challan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
