# Generated by Django 5.2.5 on 2025-10-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0174_alter_accountsgeneralledger_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='debit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.debitnote'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
    ]
