# Generated by Django 5.0.3 on 2025-10-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0174_purchaseorder_round_off_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='directpurchaseinvoice',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnchallan',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reworkdeliverychallan',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
