# Generated by Django 5.2.5 on 2025-10-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0175_accountsgeneralledger_debit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gl_purchase_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
