# Generated by Django 5.0.3 on 2025-10-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0175_directpurchaseinvoice_round_off_method_and_more'),
        ('itemmaster', '0176_accountsgeneralledger_purchase_account_and_more'),
    ]

    operations = [
    ]
