# Generated by Django 5.0.3 on 2025-10-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0177_merge_20251029_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='round_off',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
