# Generated by Django 5.0.3 on 2025-10-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0178_debitnote_round_off_debitnote_round_off_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_invoice_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnoteitemdetails',
            name='purchase_return_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
