# Generated by Django 5.2.5 on 2025-10-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0179_alter_goodsreceiptnoteitemdetails_purchase_invoice_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directpurchaseinvoice',
            name='item_detail',
            field=models.ManyToManyField(blank=True, to='itemmaster.directpurchaseinvoiceitemdetails'),
        ),
    ]
