# Generated by Django 5.0.3 on 2025-11-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0180_alter_directpurchaseinvoice_item_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='enable_variation',
            field=models.BooleanField(default=False),
        ),
    ]
