# Generated by Django 5.0.3 on 2025-11-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0181_itemmaster_enable_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='directpurchaseinvoice',
            name='supplier_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
