# Generated by Django 5.2.5 on 2025-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0182_alter_companyaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='exchange_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directpurchaseinvoice',
            name='exchange_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
