# Generated by Django 5.2.5 on 2025-11-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0183_debitnote_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseretunbatch',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
