# Generated by Django 5.0.3 on 2025-11-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0184_alter_purchaseretunbatch_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitnote',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='directpurchaseinvoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
