# Generated by Django 5.2.5 on 2025-11-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0184_alter_purchaseretunbatch_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstnaturetransaction',
            name='cess_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gstnaturetransaction',
            name='cgst_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gstnaturetransaction',
            name='igst_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gstnaturetransaction',
            name='sgst_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
