# Generated by Django 5.2.5 on 2025-11-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0185_alter_debitnote_exchange_rate_and_more'),
        ('itemmaster', '0185_alter_gstnaturetransaction_cess_rate_and_more'),
    ]

    operations = [
    ]
