# Generated by Django 5.2.5 on 2025-11-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0188_alter_termsconditions_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberingseries',
            name='resource',
            field=models.CharField(choices=[('Pos', 'Pos'), ('Purchase Order', 'Purchase Order'), ('Goods Inward Note', 'Goods Inward Note'), ('Goods Receipt Note', 'Goods Receipt Note'), ('Quality Inspection Report', 'Quality Inspection Report'), ('Rework Delivery Challan', 'Rework Delivery Challan'), ('Purchase Return Challan', 'Purchase Return Challan'), ('Direct Purchase Invoice', 'Direct Purchase Invoice'), ('Purchase Invoice', 'Purchase Invoice'), ('Quotations', 'Quotations'), ('SalesOrder', 'SalesOrder'), ('SalesOrder Delivery Challan', 'SalesOrder Delivery Challan'), ('Payment Voucher', 'Payment Voucher'), ('Target', 'Target'), ('Sales Invoice', 'Sales Invoice'), ('Debit Note', 'Debit Note'), ('Sales Return', 'Sales Return'), ('Receipt Voucher', 'Receipt Voucher')], max_length=50),
        ),
    ]
