# Generated by Django 5.2.5 on 2025-11-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0189_alter_numberingseries_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testStaanTable',
        ),
    ]
