# Generated by Django 5.0.3 on 2025-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0190_delete_teststaantable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='chart_date_format',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
