# Generated by Django 5.0.3 on 2025-11-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0191_alter_debitnoteaccount_cess_and_more'),
        ('itemmaster', '0191_reporttemplate_chart_date_format'),
    ]

    operations = [
    ]
