# Generated by Django 5.2.5 on 2025-11-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0192_alter_numberingseries_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymaster',
            name='purchase_return_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='sales_pending_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_pending_account', to='itemmaster.accountsmaster'),
        ),
        migrations.AddField(
            model_name='companymaster',
            name='sales_return_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_return_account', to='itemmaster.accountsmaster'),
        ),
    ]
