# Generated by Django 5.2.5 on 2025-11-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0193_companymaster_purchase_return_account_and_more'),
        ('itemmaster2', '0150_salesreturn_is_account_general_ledger_upated'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='sales_return_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesreturn'),
        ),
    ]
