# Generated by Django 5.0.3 on 2025-11-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0192_merge_20251124_1750'),
        ('itemmaster', '0193_companymaster_purchase_return_account_and_more'),
    ]

    operations = [
    ]
