# Generated by Django 5.2.5 on 2025-11-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0194_accountsgeneralledger_sales_return_voucher_no'),
        ('itemmaster', '0195_alter_termsconditions_module'),
    ]

    operations = [
    ]
