# Generated by Django 5.2.5 on 2025-11-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0196_merge_20251128_1948'),
        ('itemmaster2', '0153_creditnote_is_account_general_ledger_upated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='credit_note_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.creditnote'),
        ),
    ]
