# Generated by Django 5.2.5 on 2025-12-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0197_accountsgeneralledger_credit_note_voucher_no'),
        ('itemmaster2', '0160_receiptvoucher_is_account_general_ledger_upated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsgeneralledger',
            name='receipt_voucher_voucher_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.receiptvoucher'),
        ),
    ]
