# Generated by Django 5.2.5 on 2025-12-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0199_purchasepaiddetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasepaiddetails',
            old_name='receipt_voucher',
            new_name='payment_voucher',
        ),
    ]
