# Generated by Django 5.2.5 on 2025-12-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0007_alter_enquirydatas_status'),
        ('itemmaster', '0200_rename_receipt_voucher_purchasepaiddetails_payment_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstock',
            name='conference',
        ),
        migrations.AddField(
            model_name='itemstock',
            name='conference_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EnquriFromapi.conferencedata'),
        ),
    ]
