# Generated by Django 5.2.5 on 2025-12-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0201_remove_itemstock_conference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='stock_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.itemstock'),
        ),
    ]
