"""
Django settings for Staanenquiryfromwithazure project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8yl-hpyid+th##7(-8h-dhom9m9^q*8+uesbvybfc50b-t9v4h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*" , "localhost"]
# CSRF_TRUSTED_ORIGINS = ["http://localhost:3000", "https://www.maxnik.org"]
# 
# ALLOWED_HOSTS = ["13.126.210.218", 'www.maxnik.org', "maxnik.org"]
# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # installed packages
    "rest_framework",
    "corsheaders",
    'graphene_django',
    'rest_framework_swagger',  # Swagger
    'drf_yasg',  # Yet Another Swagger generator
    'django_dbml',   # django model to dbml
    # other apps
    'EnquriFromapi',
    'itemmaster',
    'itemmaster2',
    "userManagement"
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "Staanenquiryfromwithazure.middleware.microsoft_auth.MicrosoftTokenAuthMiddleware",
    'Staanenquiryfromwithazure.middleware.timezone_adjustment.TimezoneAdjustmentMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    # "https://www.maxnikerp.com",
    # "https://maxnikerp.com"
]

GRAPHENE = {
    'SCHEMA': 'Staanenquiryfromwithazure.schema.schema'
}

CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'DELETE',
    'OPTIONS',
]

CORS_ALLOW_HEADERS = [
    'Accept',
    'Accept-Encoding',
    'Authorization',
    'Content-Type',
    'Origin',
    'User-Agent',
]

CORS_ALLOW_CREDENTIALS = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'  # Outlook SMTP server
EMAIL_PORT = 587  # Port for TLS
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'marketing@staan.in'  # Your Outlook email address
EMAIL_HOST_PASSWORD = 'Sika@2025'
# EMAIL_HOST_USER = 'digital@staan.in'  # Your Outlook email address
# EMAIL_HOST_PASSWORD = 'Waw72429'

ROOT_URLCONF = 'Staanenquiryfromwithazure.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Staanenquiryfromwithazure.wsgi.application'
LOGIN_REDIRECT_URL = '/dashboard/'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# """live server DataBase"""
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'staan_live',
#         'USER': 'StaanErp',
#         'PASSWORD': 'StaanDev',
#         'HOST': 'staandatabase-2.cjkxnr9xutf0.ap-south-1.rds.amazonaws.com',
#         'PORT': '5432',
#     }
# }
 

# test data
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'Maxnik_Test',
#         'USER': 'StaanErp',
#         'PASSWORD': 'StaanDev',
#         'HOST': 'staandatabase-2.cjkxnr9xutf0.ap-south-1.rds.amazonaws.com',
#         'PORT': '5432',
#     }
# }

# """Local server DataBase"""
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'staanErp',
#         'USER': 'postgres',
#         'PASSWORD': 'Staan@2023',
#         'HOST': '192.168.1.5',
#         'PORT': '5432'
#     }
# }

 
# update data base
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('NAME'),
        'USER': config('USER'),
        'PASSWORD': config('PASSWORD'),
        'HOST': config('HOST'),
        'PORT': config('PORT')
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Image_data
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

USE_L10N = False

LOGIN_URL = '/login/'  # or whatever your login URL is

DATE_INPUT_FORMATS = ['%d/%m/%Y']


# live
# CURRENT_CLIENT_ID = "3c30e362-b108-49d2-b3b4-37fe01f4941d"
# CURRENT_AUTHORITY = "2708cf11-c83a-466f-9399-671ebba3e8fc"
# "local"
CURRENT_CLIENT_ID = "52a3b712-cbab-461d-a03d-a6b234a9ed21"
CURRENT_AUTHORITY = "2708cf11-c83a-466f-9399-671ebba3e8fc"
