from django.contrib import admin

from itemmaster2.models import CreditNote, CreditNoteComboItemDetails, CreditNoteItemDetails
from .models import NumberingSeries
from .models import *


admin.site.register(CompanyMaster)
admin.site.register(BankDetails)
admin.site.register(ReportTemplate)
admin.site.register(ItemMasterHistory)
admin.site.register(EditListView)
admin.site.register(Hsn)
admin.site.register(HsnEffectiveDate)
admin.site.register(HsnType)
admin.site.register(GstRate)
admin.site.register(Item_Groups_Name)
admin.site.register(UOM)
admin.site.register(Category)
admin.site.register(AccountsgroupType)
admin.site.register(AccountsGroup)
admin.site.register(AccountsMaster)
admin.site.register(AccountsGeneralLedger)
admin.site.register(ItemMaster)
admin.site.register(ItemType)
admin.site.register(Item_Indicator)
admin.site.register(Alternate_unit)
admin.site.register(TDSMaster)
admin.site.register(TCSMaster)
admin.site.register(TdsTcsEffectiveDate)
admin.site.register(Store)
admin.site.register(StockSerialHistory)
admin.site.register(StockHistoryLog)
admin.site.register(StockHistory)
admin.site.register(ResourcePosType)
admin.site.register(SerialNumbers)
admin.site.register(NumberingSeriesLinking)
admin.site.register(ItemStock)
admin.site.register(BatchNumber)
admin.site.register(InventoryHandler)
admin.site.register(ItemInventoryApproval)
admin.site.register(Item_Combo)
admin.site.register(display_group)
admin.site.register(Contact_type)
admin.site.register(ContactDetalis)
admin.site.register(CompanyAddress)
admin.site.register(SupplierFormData)
admin.site.register(SupplierFormGstEffectiveDate) 
admin.site.register(CurrencyMaster)
admin.site.register(CurrencyExchange)
admin.site.register(SalesOrder)
admin.site.register(paymentMode)
admin.site.register(FinishedGoods)
admin.site.register(RawMaterial)
admin.site.register(Scrap)
admin.site.register(Routing)
admin.site.register(Bom)
admin.site.register(SalesOrderItem)
admin.site.register(CustomerGroups)
admin.site.register(SupplierGroups) 
admin.site.register(NumberingSeries)
admin.site.register(BomStatus)
admin.site.register(BomRouting)
admin.site.register(GstType)
admin.site.register(WorkCenter)
admin.site.register(RawMaterialBomLink)
admin.site.register(SalesOrderItemCombo)
admin.site.register(Imagedata)
admin.site.register(Document)
admin.site.register(MrpItem)
admin.site.register(MrpSourceType)
admin.site.register(MrpMaster)
admin.site.register(Department)
admin.site.register(TermsConditions)
admin.site.register(OtherExpenses)
admin.site.register(ProductionOrderMaster)
admin.site.register(SubProductionOrders)
admin.site.register(ProductionOrderItem)
admin.site.register(ProductionOrderLinkingTable)
admin.site.register(ProductionOrderItemDetail)
"po models"
admin.site.register(purchaseOrder)
admin.site.register(purchaseOrderItemDetails)
admin.site.register(OtherExpensespurchaseOrder) 

admin.site.register(GoodsInwardNote)
admin.site.register(GoodsInwardNoteItemDetails)
admin.site.register(GoodsReceiptNote)
admin.site.register(GoodsReceiptNoteItemDetails)

admin.site.register(DebitNoteItemDetail)
admin.site.register(DebitNoteOtherIncomeCharge)
admin.site.register(DebitNoteAccount)
admin.site.register(DebitNote)

 

admin.site.register(QualityInspectionsReportItemDetails)
admin.site.register(QualityInspectionReport)
admin.site.register(PurchaseInvoiceImport)
admin.site.register(PurchaseInvoiceImportLine)
admin.site.register(DirectPurchaseInvoiceItemDetails)
admin.site.register(DirectPurchaseinvoice)
admin.site.register(DirectPurchaseInvoiceAccount)

admin.site.register(BomCostVariation)
admin.site.register(ProductionOrderFinishedGoods)
admin.site.register(ProductionOrderRawMaterials)
admin.site.register(ProductionOrderOtherCharges)
admin.site.register(ProductionOrderProcessRoute)
admin.site.register(ProductionOrderScrap)

""" DC"""

admin.site.register(CommanStatus)
admin.site.register(ReworkDeliveryChallanItemDetails)
admin.site.register(ReworkDeliveryChallan)

admin.site.register(MaterialRequestFor)
admin.site.register(MaterialRequestItemDetails)
admin.site.register(MaterialRequestMaster)
admin.site.register(PurchaseInvoice)
admin.site.register(PurchaseInvoiceItemDetails)

admin.site.register(PurchaseRetunBatch)
admin.site.register(PurchaseReturnChallanItemDetails)
admin.site.register(PurchaseReturnChallan) 

 

admin.site.register(CommanHsnEffectiveDate)


admin.site.register(UserGroup)

admin.site.register(GSTNatureTransaction)

admin.site.register(CreditNote)
admin.site.register(CreditNoteItemDetails)
admin.site.register(CreditNoteComboItemDetails)