# Generated by Django 5.1.1 on 2025-03-17 07:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usermanagement',
        #     name='user_group',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
        #                             to='itemmaster.usergroup'),
        # ),
        # migrations.AddField(
        #     model_name='roles',
        #     name='history_details',
        #     field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        # ),
        # migrations.AddField(
        #     model_name='usermanagement',
        #     name='history_details',
        #     field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        # ),
        # migrations.CreateModel(
        #     name='Holidays',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=50)),
        #         ('no_of_days', models.DecimalField(decimal_places=3, max_digits=5)),
        #         ('from_date', models.DateTimeField(blank=True, null=True)),
        #         ('to_date', models.DateTimeField(blank=True, null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('created_by',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createdHolidays',
        #                            to=settings.AUTH_USER_MODEL)),
        #         ('history_details', models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory')),
        #         ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
        #                                           related_name='modifiedHolidays', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='LeaveType',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=50)),
        #         ('leave_type',
        #          models.CharField(choices=[('Paid', 'Paid'), ('Loss Of Pay', 'Loss Of Pay')], max_length=20)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('created_by',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createdLeaveType',
        #                            to=settings.AUTH_USER_MODEL)),
        #         ('history_details', models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory')),
        #         ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
        #                                           related_name='modifiedLeaveType', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='LeaveAlloted',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('from_date', models.DateTimeField(blank=True, null=True)),
        #         ('to_date', models.DateTimeField(blank=True, null=True)),
        #         ('allotted_days', models.DecimalField(decimal_places=3, max_digits=5)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('created_by',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createdLeaveAlloted',
        #                            to=settings.AUTH_USER_MODEL)),
        #         ('employee_id',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee')),
        #         ('history_details', models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory')),
        #         ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
        #                                           related_name='modifiedLeaveAlloted', to=settings.AUTH_USER_MODEL)),
        #         ('user_group',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.usergroup')),
        #         ('leave_type',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.leavetype')),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Leave',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('leave_day_type',
        #          models.CharField(choices=[('Half Day', 'Half Day'), ('Full Day', 'Full Day')], max_length=10)),
        #         ('from_date', models.DateTimeField(blank=True, null=True)),
        #         ('to_date', models.DateTimeField(blank=True, null=True)),
        #         ('applied_days', models.DecimalField(decimal_places=3, max_digits=5)),
        #         ('reason', models.CharField(max_length=250)),
        #         ('approved_days', models.DecimalField(decimal_places=3, max_digits=5)),
        #         ('current_balance', models.DecimalField(decimal_places=3, max_digits=5)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('created_by',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createdLeave',
        #                            to=settings.AUTH_USER_MODEL)),
        #         ('employee_id',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee')),
        #         ('history_details', models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory')),
        #         ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
        #                                           related_name='modifiedLeave', to=settings.AUTH_USER_MODEL)),
        #         (
        #         'status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
        #         ('leave_type',
        #          models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.leavetype')),
        #     ],
        # ),
    ]
