# Generated by Django 5.0.3 on 2025-03-18 06:01
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_custom_migration'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='holidays',
        #     name='from_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='holidays',
        #     name='to_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='leave',
        #     name='from_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='leave',
        #     name='to_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='leavealloted',
        #     name='from_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='leavealloted',
        #     name='to_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='holidays',
        #     name='no_of_days',
        #     field=models.DecimalField(decimal_places=0, max_digits=5),
        # ),
        # migrations.AlterField(
        #     model_name='leave',
        #     name='applied_days',
        #     field=models.DecimalField(decimal_places=0, max_digits=5),
        # ),
        # migrations.AlterField(
        #     model_name='leave',
        #     name='approved_days',
        #     field=models.DecimalField(decimal_places=0, max_digits=5),
        # ),
        # migrations.AlterField(
        #     model_name='leave',
        #     name='current_balance',
        #     field=models.DecimalField(decimal_places=0, max_digits=5),
        # ),
        # migrations.AlterField(
        #     model_name='leavealloted',
        #     name='allotted_days',
        #     field=models.DecimalField(decimal_places=0, max_digits=5),
        # ),
    ]
