# Generated by Django 5.1.1 on 2025-03-20 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_alter_holidays_from_date_alter_holidays_no_of_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_education',
            field=models.CharField(blank=True, choices=[('Unskilled Labour', 'Unskilled Labour'), ('Skilled Labour', 'Skilled Labour'), ('10th', '10th'), ('12th', '12th'), ('ITI', 'ITI'), ('Diploma', 'Diploma'), ('Graduates', 'Graduates'), ('Masters', 'Masters')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='esi_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit ESI number.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='training',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='uan_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='week_off_days',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
