# Generated by Django 5.1.3 on 2025-03-18 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_initial'),
        ('userManagement', '0004_alter_holidays_from_date_alter_holidays_no_of_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.usergroup'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='applied_days',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='current_balance',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.leavetype'),
        ),
    ]
