# Generated by Django 5.1.3 on 2025-03-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_leave_user_group_alter_leave_applied_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved_days',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
