# Generated by Django 5.1.1 on 2025-03-20 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_employee_employee_education_employee_esi_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Employee_user_id', to='userManagement.usermanagement'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='week_off_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
