# Generated by Django 5.1.3 on 2025-03-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_alter_leave_approved_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavealloted',
            name='taken_leave',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
