# Generated by Django 5.1.1 on 2025-03-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_remove_employee_user_id_employee_user_and_more'),
        ('userManagement', '0007_leavealloted_taken_leave'),
    ]

    operations = [
    ]
