# Generated by Django 5.1.1 on 2025-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0008_merge_20250320_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
