# Generated by Django 5.1.3 on 2025-03-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_alter_employee_employee_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='leavealloted',
            name='user_group',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_alloted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.leavealloted'),
        ),
    ]
