# Generated by Django 5.1.3 on 2025-03-25 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_initial'),
        ('userManagement', '0010_remove_leave_leave_type_remove_leave_user_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('check_in', models.TimeField(default=False)),
                ('check_out', models.TimeField(default=False)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('over_time_hours', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('break_hours', models.TimeField(default=False)),
                ('late_in_hours', models.TimeField(default=False)),
                ('late_out_hours', models.TimeField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createdAttendanceRegister', to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee')),
                ('history_details', models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory')),
                ('holidays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.holidays')),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.leave')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifiedAttendanceRegister', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
            ],
        ),
    ]
