# Generated by Django 5.1.1 on 2025-03-25 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0010_remove_leave_leave_type_remove_leave_user_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
