# Generated by Django 5.1.1 on 2025-03-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0011_usermanagement_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
