# Generated by Django 5.1.3 on 2025-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0011_attendanceregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceregister',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='break_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='late_in_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendanceregister',
            name='late_out_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
