# Generated by Django 5.1.3 on 2025-03-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0012_remove_attendanceregister_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceregister',
            name='over_time_hours',
        ),
        migrations.RemoveField(
            model_name='attendanceregister',
            name='work_hours',
        ),
    ]
