# Generated by Django 5.1.1 on 2025-03-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0012_alter_usermanagement_created_at'),
        ('userManagement', '0014_attendanceregister_over_time_hours_and_more'),
    ]

    operations = [
    ]
