# Generated by Django 5.1.3 on 2025-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0015_merge_20250326_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='break_intervals',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
