# Generated by Django 5.1.1 on 2025-03-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0015_merge_20250328_1549'),
        ('userManagement', '0016_attendanceregister_break_intervals'),
    ]

    operations = [
    ]
