# Generated by Django 5.1.3 on 2025-04-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0015_merge_20250328_1549'),
        ('userManagement', '0016_attendanceregister_break_intervals'),
    ]

    operations = [
    ]
