# Generated by Django 5.1.3 on 2025-04-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0017_merge_20250401_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='sales_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
