# Generated by Django 5.1.1 on 2025-04-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0017_merge_20250328_1807'),
        ('userManagement', '0018_usermanagement_admin_usermanagement_sales_person_and_more'),
    ]

    operations = [
    ]
