# Generated by Django 5.1.1 on 2025-04-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0019_merge_20250403_1622'),
        ('userManagement', '0019_merge_20250404_1935'),
    ]

    operations = [
    ]
