# Generated by Django 5.1.1 on 2025-04-05 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0020_merge_20250405_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='role_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_two', to='userManagement.roles'),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_one', to='userManagement.roles'),
        ),
    ]
