# Generated by Django 5.1.3 on 2025-04-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0021_usermanagement_role_2_alter_usermanagement_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='permission_parent_model',
            field=models.CharField(choices=[('Dashboard', 'Dashboard'), ('General', 'General'), ('Stock', 'Stock'), ('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Target', 'Target'), ('Report', 'Report'), ('Conference', 'Conference'), ('Accounts', 'Accounts'), ('Service', 'Service'), ('Manufacturing', 'Manufacturing'), ('HR', 'HR'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
