# Generated by Django 5.1.1 on 2025-04-29 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0022_permissionmodel_permission_parent_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.roles'),
        ),
        migrations.AlterField(
            model_name='permissionmodel',
            name='permission_parent_model',
            field=models.CharField(choices=[('Dashboard', 'Dashboard'), ('General', 'General'), ('Stock', 'Stock'), ('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Target', 'Target'), ('Report', 'Report'), ('Conference', 'Conference'), ('Accounts', 'Accounts'), ('Service', 'Service'), ('Manufacturing', 'Manufacturing'), ('HR', 'HR'), ('Table', 'Table'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
