# Generated by Django 5.1.3 on 2025-04-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0022_permissionmodel_permission_parent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodel',
            name='permission_parent_model',
            field=models.CharField(choices=[('Other', 'Other'), ('Dashboard', 'Dashboard'), ('General', 'General'), ('Stock', 'Stock'), ('Purchase', 'Purchase'), ('Sales', 'Sales'), ('Target', 'Target'), ('Report', 'Report'), ('Conference', 'Conference'), ('Accounts', 'Accounts'), ('Service', 'Service'), ('Manufacturing', 'Manufacturing'), ('HR', 'HR'), ('Table', 'Table')], default='Other', max_length=50, null=True),
        ),
    ]
