# Generated by Django 5.1.3 on 2025-05-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0023_alter_permissionmodel_permission_parent_model'),
        ('userManagement', '0023_roles_parent_role_and_more'),
    ]

    operations = [
    ]
