# Generated by Django 5.1.1 on 2025-04-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0023_alter_permissionmodel_permission_parent_model'),
        ('userManagement', '0023_roles_parent_role_and_more'),
    ]

    operations = [
    ]
