# Generated by Django 5.1.3 on 2025-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0008_alter_hsn_description'),
        ('userManagement', '0024_merge_20250502_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
