# Generated by Django 5.1.3 on 2025-05-03 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0024_merge_20250429_1932'),
        ('userManagement', '0025_paymentvoucher_history_details'),
    ]

    operations = [
    ]
