# Generated by Django 5.1.3 on 2025-05-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0026_merge_20250503_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='sales_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='service_executive',
            field=models.BooleanField(default=False),
        ),
    ]
