# Generated by Django 5.1.3 on 2025-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0008_alter_hsn_description'),
        ('userManagement', '0027_usermanagement_sales_executive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
