# Generated by Django 5.1.3 on 2025-05-15 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0008_alter_hsn_description'),
        ('userManagement', '0028_expenseclaim_history_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.imagedata'),
        ),
    ]
