# Generated by Django 5.1.3 on 2025-05-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0008_alter_hsn_description'),
        ('userManagement', '0030_alter_employee_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='pay_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PaymentVoucher_pay_via', to='itemmaster.accountsmaster'),
        ),
    ]
