# Generated by Django 5.1.1 on 2025-06-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0031_paymentvoucher_pay_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmodel',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
    ]
