# Generated by Django 5.1.3 on 2025-06-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0032_alter_permissionmodel_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedpermission',
            name='model_name',
            field=models.CharField(max_length=50),
        ),
    ]
