# Generated by Django 5.2.5 on 2025-11-20 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0190_delete_teststaantable'),
        ('userManagement', '0033_alter_allowedpermission_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='advance_details',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='pay_mode',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='pay_to',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='pay_via',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='pay_by_str',
            field=models.CharField(blank=True, choices=[('Supplier & Customer', 'Supplier & Customer'), ('Employee', 'Employee')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='pay_mode_str',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucheradvancedetails',
            name='payment_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.paymentvoucher'),
        ),
        migrations.CreateModel(
            name='PaymentVoucherAgainstInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PaymentVoucherAgainstInvoice_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PaymentVoucherAgainstInvoice_modified', to=settings.AUTH_USER_MODEL)),
                ('payment_voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.paymentvoucher')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.purchaseinvoice')),
            ],
        ),
    ]
