# Generated by Django 5.2.5 on 2025-11-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0190_delete_teststaantable'),
        ('userManagement', '0034_remove_paymentvoucher_advance_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucherpayto',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentvoucherpayto',
            name='modified_by',
        ),
        migrations.RenameField(
            model_name='paymentvoucher',
            old_name='pay_by_str',
            new_name='pay_by',
        ),
        migrations.RenameField(
            model_name='paymentvoucher',
            old_name='pay_mode_str',
            new_name='pay_mode',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencyexchange'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentVoucherPaymode',
        ),
        migrations.DeleteModel(
            name='PaymentVoucherPayTo',
        ),
    ]
