# Generated by Django 5.2.5 on 2025-11-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0145_remove_receiptvoucher_transfer_via'),
        ('userManagement', '0035_remove_paymentvoucherpayto_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='transfer_via',
        ),
        migrations.DeleteModel(
            name='PaymentVoucherTransferVia',
        ),
    ]
