# Generated by Django 5.2.5 on 2025-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0036_remove_paymentvoucher_transfer_via_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='transfer_via',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Neft/RTGS', 'Neft/RTGS'), ('Cheque', 'Cheque')], null=True),
        ),
    ]
