# Generated by Django 5.0.3 on 2025-11-24 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0037_paymentvoucher_transfer_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucheragainstinvoice',
            name='payment_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.paymentvoucher'),
        ),
    ]
