# Generated by Django 5.2.5 on 2025-11-27 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0037_paymentvoucher_transfer_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucheradvancedetails',
            name='payment_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.paymentvoucher'),
        ),
        migrations.AlterField(
            model_name='paymentvoucheragainstinvoice',
            name='payment_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.paymentvoucher'),
        ),
    ]
