# Generated by Django 5.2.5 on 2025-11-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0038_alter_paymentvoucheradvancedetails_payment_voucher_and_more'),
        ('userManagement', '0038_alter_paymentvoucheragainstinvoice_payment_voucher'),
    ]

    operations = [
    ]
