# Generated by Django 5.2.5 on 2025-11-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0039_merge_20251128_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucheragainstinvoice',
            name='payment_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.paymentvoucher'),
        ),
    ]
