# Generated by Django 5.2.5 on 2025-12-04 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0198_accountsgeneralledger_receipt_voucher_voucher_no'),
        ('userManagement', '0040_alter_paymentvoucheragainstinvoice_payment_voucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='blance_emp_amount',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='cus_sup_amount',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='cus_sup_id',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='emp_amount',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='is_claim',
        ),
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='pay_for',
        ),
        migrations.RemoveField(
            model_name='paymentvoucheradvancedetails',
            name='payment_voucher',
        ),
        migrations.RemoveField(
            model_name='paymentvoucheragainstinvoice',
            name='payment_voucher',
        ),
        migrations.CreateModel(
            name='PaymentVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blance_emp_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_claim', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PaymentVoucherLine_created', to=settings.AUTH_USER_MODEL)),
                ('cus_sup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PaymentVoucherLine_modified', to=settings.AUTH_USER_MODEL)),
                ('pay_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PaymentVoucherLine_pay_for', to='itemmaster.accountsmaster')),
                ('payment_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.paymentvoucher')),
            ],
        ),
        migrations.AddField(
            model_name='paymentvoucheradvancedetails',
            name='payment_voucher_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.paymentvoucherline'),
        ),
        migrations.AddField(
            model_name='paymentvoucheragainstinvoice',
            name='payment_voucher_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.paymentvoucherline'),
        ),
    ]
