# Generated by Django 5.2.5 on 2025-12-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0041_remove_paymentvoucher_blance_emp_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='is_account_general_ledger_updated',
            field=models.BooleanField(default=False),
        ),
    ]
