# Generated by Django 5.2.5 on 2025-12-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0042_paymentvoucher_is_account_general_ledger_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
