# Generated by Django 5.1.1 on 2025-03-17 07:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='emailtemplete',
        #     name='history_details',
        #     field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        # ),

        # migrations.AddField(
        #     model_name='activitytype',
        #     name='history_details',
        #     field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        # ),

        # migrations.AddField(
        #     model_name='activites',
        #     name='history_details',
        #     field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        # ),
        # migrations.AddField(
        #     model_name='salesorder_2',
        #     name='email',
        #     field=models.EmailField(blank=True, max_length=254, null=True),
        # ),
        # migrations.AddField(
        #     model_name='salesorder_2',
        #     name='email_record',
        #     field=models.ManyToManyField(blank=True, to='itemmaster2.emailrecord'),
        # ),

        # migrations.AddField(
        #     model_name='salesorder_2',
        #     name='note',
        #     field=models.ManyToManyField(blank=True, to='itemmaster2.notes'),
        # ),
        # migrations.AddField(
        #     model_name='quotations',
        #     name='email',
        #     field=models.EmailField(blank=True, max_length=254, null=True),
        # ),
        # migrations.AddField(
        #     model_name='quotations',
        #     name='email_record',
        #     field=models.ManyToManyField(blank=True, to='itemmaster2.emailrecord'),
        # ),

        # migrations.AddField(
        #     model_name='quotations',
        #     name='note',
        #     field=models.ManyToManyField(blank=True, to='itemmaster2.notes'),
        # ),
    ]
