# Generated by Django 5.1.1 on 2025-03-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0002_initial'),
        ('itemmaster2', '0002_custom_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.contactdetalis'),
        ),
    ]
