# Generated by Django 5.1.1 on 2025-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0003_leads_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites',
            name='over_due',
            field=models.BooleanField(default=False),
        ),
    ]
