# Generated by Django 5.1.1 on 2025-03-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0004_activites_over_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='over_due',
            field=models.BooleanField(default=False),
        ),
    ]
