# Generated by Django 5.1.3 on 2025-03-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0005_leads_last_activity_leads_over_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='activites',
            name='activity_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
