# Generated by Django 5.1.3 on 2025-03-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0006_activites_activity_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activites',
            name='activity_count',
        ),
        migrations.AddField(
            model_name='leads',
            name='activity_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
