# Generated by Django 5.1.1 on 2025-04-01 10:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0004_supplierformdata_city_supplierformdata_state'),
        ('itemmaster2', '0007_remove_activites_activity_count_leads_activity_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_achievement', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetSalesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False)),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('target_months', models.ManyToManyField(blank=True, related_name='salespersons', to='itemmaster2.targetmonth')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=255)),
                ('financial_year_start', models.DateField()),
                ('financial_year_end', models.DateField()),
                ('target_module', models.CharField(max_length=50)),
                ('target_field', models.CharField(max_length=50)),
                ('total_target_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createTarget', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencyexchange')),
                ('history_details', models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifiedTarget', to=settings.AUTH_USER_MODEL)),
                ('target_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking')),
                ('target_sales_person', models.ManyToManyField(related_name='targets', to='itemmaster2.targetsalesperson')),
            ],
        ),
    ]
