# Generated by Django 5.1.3 on 2025-04-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0007_remove_activites_activity_count_leads_activity_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytype',
            name='sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='service',
            field=models.BooleanField(default=False),
        ),
    ]
