# Generated by Django 5.1.3 on 2025-04-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0008_activitytype_sales_activitytype_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='activity_count',
        ),
    ]
