# Generated by Django 5.1.1 on 2025-04-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0004_supplierformdata_city_supplierformdata_state'),
        ('itemmaster2', '0008_targetmonth_targetsalesperson_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='target_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
    ]
