# Generated by Django 5.1.1 on 2025-04-02 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0005_alter_numberingseries_resource'),
        ('itemmaster2', '0009_alter_target_target_no'),
        ('userManagement', '0017_merge_20250328_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsalesperson',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.roles'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_field',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_module',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_no',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
    ]
