# Generated by Django 5.1.3 on 2025-04-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0009_remove_leads_activity_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='call_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='meeting_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='task_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
