# Generated by Django 5.1.3 on 2025-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0010_leads_call_count_leads_meeting_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='mail_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
