# Generated by Django 5.1.1 on 2025-04-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0010_targetsalesperson_role_alter_target_target_field_and_more'),
        ('itemmaster2', '0011_leads_mail_count'),
    ]

    operations = [
    ]
