# Generated by Django 5.1.1 on 2025-04-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0012_merge_20250404_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='target_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_field',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_module',
            field=models.CharField(max_length=50),
        ),
    ]
