# Generated by Django 5.1.1 on 2025-04-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0012_merge_20250403_1622'),
        ('itemmaster2', '0013_target_target_mode_alter_target_target_field_and_more'),
    ]

    operations = [
    ]
