# Generated by Django 5.1.1 on 2025-04-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0014_merge_20250405_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='won_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
