# Generated by Django 5.1.3 on 2025-05-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0015_leads_won_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplete',
            name='mail_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplete',
            name='whats_app_template',
            field=models.BooleanField(default=False),
        ),
    ]
