# Generated by Django 5.1.3 on 2025-05-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0016_emailtemplete_mail_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplete',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
