# Generated by Django 5.1.1 on 2025-05-21 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0009_remove_tasktype_created_by_and_more'),
        ('itemmaster2', '0017_alter_emailtemplete_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallanItemComboItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_challan_itemCombo', to=settings.AUTH_USER_MODEL)),
                ('item_combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.item_combo')),
                ('itemmaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_delivery_challan_itemCombo', to=settings.AUTH_USER_MODEL)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallanItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('item_combo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_challan_item_details', to=settings.AUTH_USER_MODEL)),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn')),
                ('item_combo_itemdetails', models.ManyToManyField(blank=True, to='itemmaster2.deliverychallanitemcomboitemdetails')),
                ('itemmaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_delivery_challan_item_details', to=settings.AUTH_USER_MODEL)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_date', models.DateField()),
                ('e_way_bill', models.CharField(max_length=20)),
                ('e_way_bill_date', models.DateField(blank=True, null=True)),
                ('customer_po_no', models.CharField(max_length=20)),
                ('customer_po_date', models.DateField(blank=True, null=True)),
                ('consignee_gstin_type', models.CharField(blank=True, max_length=50, null=True)),
                ('consignee_gstin', models.CharField(max_length=15)),
                ('consignee_state', models.CharField(max_length=20)),
                ('consignee_place_of_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('terms_conditions_text', models.TextField(blank=True, null=True)),
                ('igst', models.JSONField(blank=True, null=True)),
                ('sgst', models.JSONField(blank=True, null=True)),
                ('cgst', models.JSONField(blank=True, null=True)),
                ('before_tax', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nett_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('own_vehicle', models.JSONField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True)),
                ('transport_id', models.CharField(blank=True, max_length=50, null=True)),
                ('courier', models.JSONField(blank=True, null=True)),
                ('other_model', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata')),
                ('consignee_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan_consignee_address', to='itemmaster.companyaddress')),
                ('consignee_contact_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan_consignee_contact_person', to='itemmaster.contactdetalis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_challan', to=settings.AUTH_USER_MODEL)),
                ('dc_no', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan_department', to='itemmaster.department')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_delivery_challan', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan_sales_person', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
                ('terms_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions')),
                ('item_details', models.ManyToManyField(blank=True, to='itemmaster2.deliverychallanitemdetails')),
            ],
            options={
                'verbose_name': 'Sales Order Delivery Challan',
                'verbose_name_plural': 'Sales Order Delivery Challans',
                'ordering': ['-created_at'],
            },
        ),
    ]
