# Generated by Django 5.1.1 on 2025-05-22 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0009_remove_tasktype_created_by_and_more'),
        ('itemmaster2', '0018_deliverychallanitemcomboitemdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverychallanitemcomboitemdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemcomboitemdetails',
            name='item_combo',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemcomboitemdetails',
            name='itemmaster',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemcomboitemdetails',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemcomboitemdetails',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemdetails',
            name='item_combo_itemdetails',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemdetails',
            name='hsn',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemdetails',
            name='itemmaster',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemdetails',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='deliverychallanitemdetails',
            name='uom',
        ),
        migrations.CreateModel(
            name='SalesOrder_2_DeliveryChallanItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_challan_item_details', to=settings.AUTH_USER_MODEL)),
                ('item_combo_itemdetails', models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_temcomboitemdetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_delivery_challan_item_details', to=settings.AUTH_USER_MODEL)),
                ('sales_order_item_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_itemdetails')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store')),
            ],
            options={
                'verbose_name': 'Sales Order Item Detail Delivery Challan',
                'verbose_name_plural': 'Sales Order Item Details Delivery Challans',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder_2_DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_date', models.DateField()),
                ('e_way_bill', models.CharField(max_length=20)),
                ('e_way_bill_date', models.DateField(blank=True, null=True)),
                ('terms_conditions_text', models.TextField(blank=True, null=True)),
                ('igst', models.JSONField(blank=True, null=True)),
                ('sgst', models.JSONField(blank=True, null=True)),
                ('cgst', models.JSONField(blank=True, null=True)),
                ('before_tax', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nett_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=20, null=True)),
                ('transport_id', models.CharField(blank=True, max_length=50, null=True)),
                ('docket_no', models.CharField(blank=True, max_length=30, null=True)),
                ('docket_date', models.DateField(blank=True, null=True)),
                ('other_model', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_challan', to=settings.AUTH_USER_MODEL)),
                ('dc_no', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_delivery_challan', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
                ('terms_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions')),
                ('item_details', models.ManyToManyField(to='itemmaster2.salesorder_2_deliverychallanitemdetails')),
            ],
            options={
                'verbose_name': 'Sales Order Delivery Challan',
                'verbose_name_plural': 'Sales Order Delivery Challans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DeliveryChallan',
        ),
        migrations.DeleteModel(
            name='DeliveryChallanItemComboItemDetails',
        ),
        migrations.DeleteModel(
            name='DeliveryChallanItemDetails',
        ),
    ]
