# Generated by Django 5.1.1 on 2025-05-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0019_remove_deliverychallanitemcomboitemdetails_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_deliverychallan',
            name='e_way_bill',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
