# Generated by Django 5.1.1 on 2025-05-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0009_remove_tasktype_created_by_and_more'),
        ('itemmaster2', '0020_alter_salesorder_2_deliverychallan_e_way_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2',
            name='dc_links',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_deliverychallan'),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.batchnumber'),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='serial',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='stock_reduce',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorder_2_itemdetails',
            name='dc_draft_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_itemdetails',
            name='dc_submit_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
