# Generated by Django 5.1.1 on 2025-05-26 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0014_alter_numberingseries_resource'),
        ('itemmaster2', '0021_salesorder_2_dc_links_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder_2_DeliverChallanItemCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_reduce', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.batchnumber')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_challan_item_combo', to=settings.AUTH_USER_MODEL)),
                ('item_combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_temcomboitemdetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_delivery_challan_item_combo', to=settings.AUTH_USER_MODEL)),
                ('serial', models.ManyToManyField(blank=True, to='itemmaster.serialnumbers')),
            ],
        ),
        migrations.AlterField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='item_combo_itemdetails',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_deliverchallanitemcombo'),
        ),
    ]
