# Generated by Django 5.1.1 on 2025-05-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0014_alter_numberingseries_resource'),
        ('itemmaster2', '0022_salesorder_2_deliverchallanitemcombo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='salesorder_2_temcomboitemdetails',
            name='dc_draft_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_temcomboitemdetails',
            name='dc_submit_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
