# Generated by Django 5.1.3 on 2025-05-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0015_alter_termsconditions_module'),
        ('itemmaster2', '0023_salesorder_2_deliverchallanitemcombo_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_deliverychallan',
            name='dc_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
    ]
