# Generated by Django 5.1.3 on 2025-05-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0024_alter_salesorder_2_deliverychallan_dc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='item_combo_itemdetails',
            field=models.ManyToManyField(blank=True, null=True, to='itemmaster2.salesorder_2_deliverchallanitemcombo'),
        ),
    ]
