# Generated by Django 5.1.3 on 2025-05-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0015_alter_termsconditions_module'),
        ('itemmaster2', '0025_alter_salesorder_2_deliverychallanitemdetails_item_combo_itemdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='item_combo_itemdetails',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_deliverchallanitemcombo'),
        ),
        migrations.AlterField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='serial',
            field=models.ManyToManyField(blank=True, null=True, to='itemmaster.serialnumbers'),
        ),
    ]
