# Generated by Django 5.1.3 on 2025-05-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0015_alter_termsconditions_module'),
        ('itemmaster2', '0026_alter_salesorder_2_deliverychallanitemdetails_item_combo_itemdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.department'),
        ),
    ]
