# Generated by Django 5.1.3 on 2025-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0027_salesorder_2_deliverychallan_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverychallan',
            name='department',
        ),
    ]
