# Generated by Django 5.1.3 on 2025-05-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0015_alter_termsconditions_module'),
        ('itemmaster2', '0028_remove_salesorder_2_deliverychallan_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='serial',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
    ]
