# Generated by Django 5.1.3 on 2025-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0029_alter_salesorder_2_deliverychallanitemdetails_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='comman_store',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
