# Generated by Django 5.1.1 on 2025-05-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0030_salesorder_2_deliverychallan_comman_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='other_income_charge',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_otherincomecharges'),
        ),
    ]
