# Generated by Django 5.1.1 on 2025-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0031_salesorder_2_deliverychallan_other_income_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
