# Generated by Django 5.1.1 on 2025-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0032_salesorder_2_deliverchallanitemcombo_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_otherincomecharges',
            name='sales_invoice_child_other_income_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
