# Generated by Django 5.1.3 on 2025-06-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0017_stockhistory_is_delete'),
        ('itemmaster2', '0033_salesorder_2_otherincomecharges_sales_invoice_child_other_income_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_invoice_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_invoice', to=settings.AUTH_USER_MODEL)),
                ('dc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallan')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_sales_invoice', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_invoice_item_detail', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_sales_invoice_item_detail', to=settings.AUTH_USER_MODEL)),
                ('so_dc_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallanitemdetails')),
            ],
        ),
    ]
