# Generated by Django 5.1.3 on 2025-06-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0034_alter_salesorder_2_deliverychallanitemdetails_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverychallan',
            name='comman_store',
        ),
    ]
