# Generated by Django 5.1.1 on 2025-06-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0017_stockhistory_is_delete'),
        ('itemmaster2', '0034_alter_salesorder_2_deliverychallanitemdetails_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='cgst',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='igst',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='item_total_befor_tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='other_charges_befor_tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='other_income_charge',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_otherincomecharges'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='round_off',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sgst',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='so_dc_item',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_deliverychallanitemdetails'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tax_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='taxable_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='terms_conditions_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SalesInvoiceItemDetails',
        ),
    ]
