# Generated by Django 5.1.1 on 2025-06-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0035_salesinvoice_cgst_salesinvoice_igst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_otherincomecharges',
            name='sales_invoice_child_other_income_total',
        ),
        migrations.AddField(
            model_name='salesorder_2_otherincomecharges',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_income_charges', to='itemmaster2.salesorder_2_otherincomecharges'),
        ),
    ]
