# Generated by Django 5.1.3 on 2025-06-02 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0017_stockhistory_is_delete'),
        ('itemmaster2', '0035_remove_salesorder_2_deliverychallan_comman_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='comman_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store'),
        ),
    ]
