# Generated by Django 5.1.3 on 2025-06-03 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0017_stockhistory_is_delete'),
        ('itemmaster2', '0036_salesorder_2_deliverychallan_comman_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverychallan',
            name='transport_id',
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata'),
        ),
    ]
