# Generated by Django 5.1.1 on 2025-06-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0036_remove_salesorder_2_otherincomecharges_sales_invoice_child_other_income_total_and_more'),
        ('itemmaster2', '0037_remove_salesorder_2_deliverychallan_transport_id_and_more'),
    ]

    operations = [
    ]
