# Generated by Django 5.1.1 on 2025-06-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0038_merge_20250606_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='all_stock_reduce',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='dc',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dc',
            field=models.ManyToManyField(to='itemmaster2.salesorder_2_deliverychallan'),
        ),
    ]
