# Generated by Django 5.1.1 on 2025-06-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0039_salesorder_2_deliverychallan_all_stock_reduce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='dc',
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster2.salesinvoice'),
        ),
    ]
