# Generated by Django 5.1.1 on 2025-06-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0017_stockhistory_is_delete'),
        ('itemmaster2', '0040_remove_salesinvoice_dc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.department'),
        ),
    ]
