# Generated by Django 5.1.1 on 2025-06-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0041_salesinvoice_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_dc',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_deliverychallan'),
        ),
    ]
