# Generated by Django 5.1.1 on 2025-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0019_alter_numberingseries_resource_and_more'),
        ('itemmaster2', '0042_salesinvoice_sales_dc'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
