# Generated by Django 5.1.3 on 2025-06-16 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0019_alter_numberingseries_resource_and_more'),
        ('itemmaster2', '0043_salesorder_2_deliverychallan_history_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesInvoice_buyer', to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesInvoice_buyer_address', to='itemmaster.companyaddress'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesInvoice_buyer_contact_person', to='itemmaster.contactdetalis'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer_gstin_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer_place_of_supply',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
