# Generated by Django 5.1.3 on 2025-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0019_alter_numberingseries_resource_and_more'),
        ('itemmaster2', '0044_salesinvoice_buyer_salesinvoice_buyer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
