# Generated by Django 4.2.2 on 2025-06-17 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster2', '0045_salesinvoice_history_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceItemCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('after_discount_value_for_per_item', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_invoice_item_detail_item_combo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='so_dc_item',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='discount_final_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='overall_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='overall_discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='invoice_draft_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='invoice_submit_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='invoice_draft_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='invoice_submit_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='SalesInvoiceItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('after_discount_value_for_per_item', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('final_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_invoice_item_detail', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallanitemdetails')),
                ('item_combo', models.ManyToManyField(blank=True, to='itemmaster2.salesinvoiceitemcombo')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_sales_invoice_item_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salesinvoiceitemcombo',
            name='item_combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverchallanitemcombo'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemcombo',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_sales_invoice_item_detail_item_combo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='item_detail',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesinvoiceitemdetail'),
        ),
    ]
