# Generated by Django 5.1.3 on 2025-06-20 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0019_alter_numberingseries_resource_and_more'),
        ('itemmaster2', '0046_salesinvoiceitemcombo_remove_salesinvoice_so_dc_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder_2_SalesReturnItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_return_item_details', to=settings.AUTH_USER_MODEL)),
                ('dc_item_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallanitemdetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_sales_return_item_details', to=settings.AUTH_USER_MODEL)),
                ('sales_order_item_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_itemdetails')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_date', models.DateField()),
                ('e_way_bill', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('terms_conditions_text', models.TextField(blank=True, null=True)),
                ('igst', models.JSONField(blank=True, null=True)),
                ('sgst', models.JSONField(blank=True, null=True)),
                ('cgst', models.JSONField(blank=True, null=True)),
                ('item_total_befor_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('other_charges_befor_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=3, max_digits=15)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('round_off', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UpdatedAt', models.DateTimeField(auto_now=True)),
                ('comman_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='createSalesReturn', to=settings.AUTH_USER_MODEL)),
                ('email_record', models.ManyToManyField(blank=True, to='itemmaster2.emailrecord')),
                ('history_details', models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory')),
                ('item_details', models.ManyToManyField(to='itemmaster2.salesorder_2_salesreturnitemdetails')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifiedSalesReturn', to=settings.AUTH_USER_MODEL)),
                ('note', models.ManyToManyField(blank=True, to='itemmaster2.notes')),
                ('other_income_charge', models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_otherincomecharges')),
                ('rma_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking')),
                ('sales_dc', models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_deliverychallan')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
                ('terms_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions')),
            ],
        ),
    ]
