# Generated by Django 5.1.3 on 2025-06-20 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0047_salesorder_2_salesreturnitemdetails_salesreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='item_details',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='comman_store',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='email_record',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='history_details',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='note',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='other_income_charge',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='rma_no',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='sales_dc',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='terms_conditions',
        ),
        migrations.DeleteModel(
            name='SalesOrder_2_SalesReturnItemDetails',
        ),
        migrations.DeleteModel(
            name='SalesReturn',
        ),
    ]
