# Generated by Django 4.2.2 on 2025-07-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0035_alter_gstnaturetransaction_specify_type_and_more'),
        ('itemmaster2', '0048_remove_salesreturn_item_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='gst_nature_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.gstnaturetransaction'),
        ),
        migrations.AddField(
            model_name='quotations',
            name='tcs_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotations',
            name='tds_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationsitemdetails',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationsitemdetails',
            name='tcs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationsitemdetails',
            name='tds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quotationsotherincomecharges',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
