# Generated by Django 4.2.2 on 2025-07-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0035_alter_gstnaturetransaction_specify_type_and_more'),
        ('itemmaster2', '0049_quotations_gst_nature_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationsitemcomboitemdetails',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.item_combo'),
        ),
    ]
