# Generated by Django 4.2.2 on 2025-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0050_quotationsitemcomboitemdetails_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2',
            name='buyer_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2',
            name='buyer_state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salesorder_2',
            name='consignee_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2',
            name='consignee_state',
            field=models.CharField(max_length=50),
        ),
    ]
