# Generated by Django 4.2.2 on 2025-07-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0038_alter_gstnaturetransaction_specify_type_and_more'),
        ('itemmaster2', '0051_alter_salesorder_2_buyer_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='cess',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='cess',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='gst_nature_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.gstnaturetransaction'),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='tcs_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='tds_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_itemdetails',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_itemdetails',
            name='tcs',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_itemdetails',
            name='tds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_otherincomecharges',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_temcomboitemdetails',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.item_combo'),
        ),
    ]
