# Generated by Django 5.1.3 on 2025-07-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0052_quotations_cess_salesorder_2_cess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsitemdetails',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
