# Generated by Django 5.1.3 on 2025-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0053_alter_quotationsitemdetails_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='tcs_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotations',
            name='tds_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationsitemdetails',
            name='tcs_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotationsitemdetails',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='quotationsitemdetails',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
