# Generated by Django 4.2.2 on 2025-07-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0054_quotations_tcs_enable_quotations_tds_enable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotations',
            name='gst_nature_transaction',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='tcs_enable',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='tcs_total',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='tds_enable',
        ),
        migrations.RemoveField(
            model_name='quotations',
            name='tds_total',
        ),
        migrations.RemoveField(
            model_name='quotationsitemdetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='quotationsitemdetails',
            name='tcs_percentage',
        ),
        migrations.RemoveField(
            model_name='quotationsitemdetails',
            name='tds',
        ),
        migrations.RemoveField(
            model_name='quotationsitemdetails',
            name='tds_percentage',
        ),
    ]
