# Generated by Django 4.2.2 on 2025-07-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0056_quotations_gst_nature_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2',
            name='tcs_total',
        ),
        migrations.RemoveField(
            model_name='salesorder_2',
            name='tds_total',
        ),
        migrations.RemoveField(
            model_name='salesorder_2_itemdetails',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='salesorder_2_itemdetails',
            name='tds',
        ),
    ]
