# Generated by Django 4.2.2 on 2025-07-07 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0038_alter_gstnaturetransaction_specify_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itemmaster2', '0057_remove_salesorder_2_tcs_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='buyer_address',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cess',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesInvoice_consignee', to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='consignee_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesInvoice_consignee_address', to='itemmaster.companyaddress'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='consignee_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesInvoice_consignee_contact_person', to='itemmaster.contactdetalis'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='consignee_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='consignee_gstin_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='consignee_place_of_supply',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='consignee_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='creadit_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer_po',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='customer_po_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tcs_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tcs_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tds_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tds_total',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='cess_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='cgst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='igst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='sgst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='tcs_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='tcs_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='tds_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='tds_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitemdetail',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalesAccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('igst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cess', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('igst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cess_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tds_percentage', models.IntegerField(blank=True, null=True)),
                ('tcs_percentage', models.IntegerField(blank=True, null=True)),
                ('tds_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tcs_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_account_ledger', to=settings.AUTH_USER_MODEL)),
                ('hsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_sales_account_ledger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_account_ledger',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesaccountledger'),
        ),
    ]
