# Generated by Django 4.2.2 on 2025-07-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0038_alter_gstnaturetransaction_specify_type_and_more'),
        ('itemmaster2', '0058_remove_salesinvoice_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesInvoice_buyer', to='itemmaster.supplierformdata'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='buyer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesInvoice_buyer_address', to='itemmaster.companyaddress'),
        ),
    ]
