# Generated by Django 4.2.2 on 2025-07-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0059_salesinvoice_buyer_salesinvoice_buyer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesaccountledger',
            name='after_discount_value_for_per_item',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesaccountledger',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesaccountledger',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesaccountledger',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesaccountledger',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cess_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='cgst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='igst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sgst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesaccountledger',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesaccountledger',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesaccountledger',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesaccountledger',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesaccountledger',
            name='tcs_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesaccountledger',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer_po_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        # migrations.AlterField(
        #     model_name='salesinvoice',
        #     name='tcs_total',
        #     field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='salesinvoice',
        #     name='tds_total',
        #     field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        # ),
    ]
