# Generated by Django 4.2.2 on 2025-07-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0060_salesaccountledger_after_discount_value_for_per_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='tcs_total',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='tds_total',
        ),
    ]
