# Generated by Django 4.2.2 on 2025-07-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0061_remove_salesinvoice_tcs_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='tcs_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='tds_total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
