# Generated by Django 4.2.2 on 2025-07-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0038_alter_gstnaturetransaction_specify_type_and_more'),
        ('itemmaster2', '0062_salesinvoice_tcs_total_salesinvoice_tds_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='gst_nature_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.gstnaturetransaction'),
        ),
    ]
