# Generated by Django 4.2.2 on 2025-07-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0063_salesinvoice_gst_nature_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='gst_nature_transaction',
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
