# Generated by Django 4.2.2 on 2025-07-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0064_remove_salesinvoice_gst_nature_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='tax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_otherincomecharges',
            name='cess_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_otherincomecharges',
            name='cgst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_otherincomecharges',
            name='igst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_otherincomecharges',
            name='sgst_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
