# Generated by Django 5.1.3 on 2025-07-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0065_salesinvoiceitemdetail_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='cess',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
