# Generated by Django 4.2.2 on 2025-07-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0066_salesorder_2_deliverychallan_cess'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2',
            name='cess_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='cgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='igst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='sgst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
