# Generated by Django 5.1.3 on 2025-07-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0067_salesorder_2_cess_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify')], max_length=20, null=True),
        ),
    ]
