# Generated by Django 5.1.3 on 2025-07-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0068_quotations_gst_nature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='gstin_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
