# Generated by Django 5.1.3 on 2025-07-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0038_alter_gstnaturetransaction_specify_type_and_more'),
        ('itemmaster2', '0069_quotations_gstin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='gst_nature_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.gstnaturetransaction'),
        ),
    ]
