# Generated by Django 5.1.3 on 2025-07-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0070_salesinvoice_gst_nature_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='gst_nature_transaction',
        ),
    ]
