# Generated by Django 5.1.3 on 2025-07-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0071_remove_salesinvoice_gst_nature_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='return_draft_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='return_submit_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
