# Generated by Django 4.2.2 on 2025-07-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0071_remove_salesinvoice_gst_nature_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoiceitemcombo',
            name='item_combo',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitemdetail',
            name='item',
        ),
        migrations.AddField(
            model_name='salesinvoiceitemcombo',
            name='item_combo',
            field=models.ManyToManyField(to='itemmaster2.salesorder_2_deliverchallanitemcombo'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='item',
            field=models.ManyToManyField(to='itemmaster2.salesorder_2_deliverychallanitemdetails'),
        ),
    ]
