# Generated by Django 5.1.3 on 2025-07-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0072_remove_salesinvoiceitemcombo_item_combo_and_more'),
        ('itemmaster2', '0072_salesorder_2_deliverychallanitemdetails_return_draft_count_and_more'),
    ]

    operations = [
    ]
