# Generated by Django 5.1.3 on 2025-07-15 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0074_remove_salesinvoice_sales_account_ledger_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='salesinvoice',
        #     name='sales_account_ledger',
        # ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='return_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        # migrations.AlterField(
        #     model_name='salesaccountledger',
        #     name='created_by',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_Direct_sales_account_ledger', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='salesaccountledger',
        #     name='modified_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_Direct_sales_account_ledger', to=settings.AUTH_USER_MODEL),
        # ),
    ]
