# Generated by Django 5.1.3 on 2025-07-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0073_remove_salesinvoice_sales_account_ledger_and_more'),
        ('itemmaster2', '0075_remove_salesinvoice_sales_account_ledger_and_more'),
    ]

    operations = [
    ]
