# Generated by Django 4.2.2 on 2025-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0076_merge_20250715_1618'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='directsalesinvoice',
        #     old_name='sales_invoice_date',
        #     new_name='direct_sales_invoice_date',
        # ),
        # migrations.RenameField(
        #     model_name='directsalesinvoice',
        #     old_name='sales_invoice_no',
        #     new_name='direct_sales_invoice_no',
        # ),
        migrations.AlterField(
            model_name='salesorder_2_itemdetails',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
