# Generated by Django 4.2.2 on 2025-07-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0077_rename_sales_invoice_date_directsalesinvoice_direct_sales_invoice_date_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='directsalesinvoice',
        #     old_name='sales_invoice_date',
        #     new_name='direct_sales_invoice_date',
        # ),
        # migrations.RenameField(
        #     model_name='directsalesinvoice',
        #     old_name='sales_invoice_no',
        #     new_name='direct_sales_invoice_no',
        # ),
        migrations.AlterField(
            model_name='quotationsotherincomecharges',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
