# Generated by Django 4.2.2 on 2025-07-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0078_rename_sales_invoice_date_directsalesinvoice_direct_sales_invoice_date_and_more'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='directsalesinvoice',
        #     old_name='sales_invoice_date',
        #     new_name='direct_sales_invoice_date',
        # ),
        # migrations.RenameField(
        #     model_name='directsalesinvoice',
        #     old_name='sales_invoice_no',
        #     new_name='direct_sales_invoice_no',
        # ),
        migrations.AddField(
            model_name='salesinvoice',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='email_record',
            field=models.ManyToManyField(blank=True, to='itemmaster2.emailrecord'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='note',
            field=models.ManyToManyField(blank=True, to='itemmaster2.notes'),
        ),
    ]
