# Generated by Django 4.2.2 on 2025-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0080_rename_sales_invoice_date_directsalesinvoice_direct_sales_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_otherincomecharges',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
