# Generated by Django 5.1.3 on 2025-07-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0076_merge_20250715_1704'),
        ('itemmaster2', '0081_alter_salesorder_2_otherincomecharges_tax'),
    ]

    operations = [
    ]
