# Generated by Django 5.1.3 on 2025-07-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0082_merge_20250716_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='lead_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitemdetail',
            name='tcs_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitemdetail',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
