# Generated by Django 5.1.3 on 2025-07-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0083_alter_leads_lead_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoiceitemdetail',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
