# Generated by Django 4.2.2 on 2025-07-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0083_alter_leads_lead_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directsalesinvoice',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify')], max_length=20, null=True),
        ),
    ]
