# Generated by Django 4.2.2 on 2025-07-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0038_alter_gstnaturetransaction_specify_type_and_more'),
        ('itemmaster2', '0084_directsalesinvoice_gst_nature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='directsalesinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencyexchange'),
        ),
    ]
