# Generated by Django 4.2.2 on 2025-07-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0084_alter_salesinvoiceitemdetail_tax'),
        ('itemmaster2', '0085_directsalesinvoice_currency'),
    ]

    operations = [
    ]
