# Generated by Django 5.1.3 on 2025-07-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0084_alter_salesinvoiceitemdetail_tax'),
        ('itemmaster2', '0085_directsalesinvoice_currency'),
    ]

    operations = [
    ]
