# Generated by Django 4.2.2 on 2025-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0086_merge_20250716_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsalesinvoice',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify')], max_length=50, null=True),
        ),
    ]
