# Generated by Django 4.2.2 on 2025-07-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0087_alter_directsalesinvoice_gst_nature_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='gstin_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
