# Generated by Django 4.2.2 on 2025-07-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0086_merge_20250717_1301'),
        ('itemmaster2', '0088_alter_quotations_gstin_type'),
    ]

    operations = [
    ]
