# Generated by Django 4.2.2 on 2025-07-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0089_merge_20250717_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
    ]
