# Generated by Django 4.2.2 on 2025-07-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0090_salesorder_2_deliverychallan_is_account_general_ledger_upated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directsalesinvoice',
            name='sales_account_ledger',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SalesAccountLedger',
        ),
    ]
