# Generated by Django 5.1.3 on 2025-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0091_remove_directsalesinvoice_sales_account_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsalesinvoiceitemdetails',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
