# Generated by Django 4.2.2 on 2025-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0042_accountsgeneralledger_direct_sales_voucher_no'),
        ('itemmaster2', '0091_remove_directsalesinvoice_sales_account_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directsalesinvoice',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='directsalesinvoice',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
    ]
