# Generated by Django 5.1.3 on 2025-07-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0040_alter_accountsgeneralledger_options'),
        ('itemmaster2', '0092_alter_directsalesinvoiceitemdetails_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsalesinvoice',
            name='direct_sales_invoice_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking'),
        ),
    ]
