# Generated by Django 4.2.2 on 2025-07-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0092_directsalesinvoice_history_details_and_more'),
        ('itemmaster2', '0093_alter_directsalesinvoice_direct_sales_invoice_no'),
    ]

    operations = [
    ]
