# Generated by Django 5.0.3 on 2025-07-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0043_companymaster_cess_account_and_more'),
        ('itemmaster2', '0094_merge_20250721_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsitemcomboitemdetails',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.item_combo'),
        ),
        migrations.AlterField(
            model_name='salesorder_2_temcomboitemdetails',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.item_combo'),
        ),
    ]
