# Generated by Django 4.2.2 on 2025-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0095_alter_quotationsitemcomboitemdetails_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='return_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
