# Generated by Django 4.2.2 on 2025-08-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0097_salesretunitemcombo_salesreturnitemdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='sales_retun',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesreturn'),
        ),
        migrations.AlterField(
            model_name='salesorder_2_deliverychallan',
            name='sales_retun',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesreturn'),
        ),
    ]
