# Generated by Django 4.2.2 on 2025-08-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0098_alter_salesinvoice_sales_retun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesretunitemcombo',
            name='after_discount_value_for_per_item',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='discount_final_total',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='overall_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='overall_discount_value',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='after_discount_value_for_per_item',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='final_value',
        ),
    ]
