# Generated by Django 5.2.5 on 2025-09-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0099_remove_salesretunitemcombo_after_discount_value_for_per_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_temcomboitemdetails',
            name='dc_draft_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2_temcomboitemdetails',
            name='dc_submit_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
