# Generated by Django 5.0.3 on 2025-09-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0012_merge_20250404_1921'),
        ('itemmaster2', '0100_alter_salesorder_2_temcomboitemdetails_dc_draft_count_and_more'),
    ]

    operations = [
    ]
