# Generated by Django 5.2.5 on 2025-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0101_merge_20250917_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsalesinvoice',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify'), ('Import Purchase', 'Import Purchase')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify'), ('Import Purchase', 'Import Purchase')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2',
            name='gst_nature_type',
            field=models.CharField(blank=True, choices=[('As per HSN', 'As per HSN'), ('Specify', 'Specify'), ('Import Purchase', 'Import Purchase')], max_length=50, null=True),
        ),
    ]
