# Generated by Django 5.2.5 on 2025-09-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0140_alter_termsconditions_module'),
        ('itemmaster2', '0102_alter_directsalesinvoice_gst_nature_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='batch',
        ),
        migrations.CreateModel(
            name='SalesOrder_2_RetunBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_stock_reduce', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.batchnumber')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_itemdetails')),
            ],
        ),
    ]
