# Generated by Django 5.2.5 on 2025-09-27 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0103_remove_salesorder_2_deliverychallanitemdetails_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_retunbatch',
            name='item_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverchallanitemcombo'),
        ),
    ]
