# Generated by Django 5.2.5 on 2025-09-27 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0104_salesorder_2_retunbatch_item_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_retunbatch',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallanitemdetails'),
        ),
    ]
