# Generated by Django 5.2.5 on 2025-09-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0105_alter_salesorder_2_retunbatch_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='salesorder_2_itemdetails',
            name='dc_draft_count',
        ),
        migrations.AddField(
            model_name='salesorder_2_itemdetails',
            name='is_have_draft',
            field=models.BooleanField(default=False),
        ),
    ]
