# Generated by Django 5.2.5 on 2025-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0106_remove_salesorder_2_deliverchallanitemcombo_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_temcomboitemdetails',
            name='dc_draft_count',
        ),
        migrations.AddField(
            model_name='salesorder_2_temcomboitemdetails',
            name='is_have_draft',
            field=models.BooleanField(default=False),
        ),
    ]
