# Generated by Django 5.2.5 on 2025-10-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0107_remove_salesorder_2_temcomboitemdetails_dc_draft_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_retunbatch',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesorder_2_deliverychallanitemdetails'),
        ),
        migrations.AlterField(
            model_name='salesorder_2_retunbatch',
            name='item_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesorder_2_deliverchallanitemcombo'),
        ),
    ]
