# Generated by Django 5.2.5 on 2025-10-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0108_alter_salesorder_2_retunbatch_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverychallan',
            name='cgst',
        ),
    ]
