# Generated by Django 5.0.3 on 2025-10-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0109_remove_salesorder_2_deliverychallan_cgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='cgst',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
