# Generated by Django 5.2.5 on 2025-10-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0110_salesorder_2_deliverychallan_cgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_deliverychallan',
            name='before_tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2_deliverychallan',
            name='nett_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
