# Generated by Django 5.0.3 on 2025-10-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0111_alter_salesorder_2_deliverychallan_before_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directsalesinvoice',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quotations',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='round_off_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
