# Generated by Django 5.2.5 on 2025-11-04 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0112_directsalesinvoice_round_off_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='item_combo',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='comman_store',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='item_details',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='other_income_charge',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='rma_no',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='sales_person',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='terms_conditions',
        ),
        migrations.RemoveField(
            model_name='salesorder_2_deliverychallan',
            name='sales_retun',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='sales_retun',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='dc_item_detail',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='itemmaster',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='sales_invoice_item_detail',
        ),
        migrations.DeleteModel(
            name='SalesRetunItemCombo',
        ),
        migrations.DeleteModel(
            name='SalesReturn',
        ),
        migrations.DeleteModel(
            name='SalesReturnItemDetails',
        ),
    ]
