# Generated by Django 5.2.5 on 2025-11-05 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0184_alter_purchaseretunbatch_qty'),
        ('itemmaster2', '0113_remove_salesreturnitemdetails_item_combo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRetunItemCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_retun_item_detail_item_combo', to=settings.AUTH_USER_MODEL)),
                ('dc_item_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverchallanitemcombo')),
                ('itemmaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_sales_retun_item_detail_item_combo', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice_item_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesinvoiceitemcombo')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_date', models.DateField()),
                ('e_way_bill', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('igst', models.JSONField(blank=True, null=True)),
                ('sgst', models.JSONField(blank=True, null=True)),
                ('cgst', models.JSONField(blank=True, null=True)),
                ('cess', models.JSONField(blank=True, null=True)),
                ('igst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cess_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tds_bool', models.BooleanField(default=False)),
                ('tcs_bool', models.BooleanField(default=False)),
                ('tds_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tcs_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('item_total_befor_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('other_charges_befor_tax', models.DecimalField(decimal_places=3, max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=3, max_digits=15)),
                ('taxable_value', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('round_off', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('round_off_method', models.CharField(blank=True, max_length=10, null=True)),
                ('net_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('terms_conditions_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comman_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.store')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='createSalesReturn', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifiedSalesReturn', to=settings.AUTH_USER_MODEL)),
                ('other_income_charge', models.ManyToManyField(blank=True, to='itemmaster2.salesorder_2_otherincomecharges')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sr_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus')),
                ('terms_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.termsconditions')),
            ],
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales_retun',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesreturn'),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverychallan',
            name='sales_retun',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesreturn'),
        ),
        migrations.CreateModel(
            name='SalesReturnItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('igst', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('cess', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('igst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cess_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tds_percentage', models.IntegerField(blank=True, null=True)),
                ('tcs_percentage', models.IntegerField(blank=True, null=True)),
                ('tds_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tcs_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_return_item_details', to=settings.AUTH_USER_MODEL)),
                ('dc_item_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallanitemdetails')),
                ('itemmaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_sales_return_item_details', to=settings.AUTH_USER_MODEL)),
                ('sales_invoice_item_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesinvoiceitemdetail')),
                ('sales_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesreturn')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.batchnumber')),
                ('item_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesretunitemcombo')),
                ('serial', models.ManyToManyField(blank=True, to='itemmaster.serialnumbers')),
                ('item_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesreturnitemdetails')),
            ],
        ),
        migrations.AddField(
            model_name='salesretunitemcombo',
            name='item_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesreturnitemdetails'),
        ),
    ]
