# Generated by Django 5.2.5 on 2025-11-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0114_salesretunitemcombo_salesreturn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_itemdetails',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2_itemdetails',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2_itemdetails',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2_itemdetails',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
