# Generated by Django 5.2.5 on 2025-11-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0115_alter_salesorder_2_itemdetails_cess_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2',
            name='dc_links',
        ),
    ]
