# Generated by Django 5.2.5 on 2025-11-06 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0116_remove_salesorder_2_dc_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2_deliverychallan',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='itemmaster2.salesorder_2'),
        ),
    ]
