# Generated by Django 5.0.3 on 2025-11-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0117_alter_salesorder_2_deliverychallan_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder_2',
            name='buyer_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2',
            name='consignee_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
