# Generated by Django 5.2.5 on 2025-11-06 13:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0186_merge_20251106_1811'),
        ('itemmaster2', '0117_alter_salesorder_2_deliverychallan_sales_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesRetunItemCombo',
            new_name='SalesReturnItemCombo',
        ),
    ]
