# Generated by Django 5.2.5 on 2025-11-07 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0186_merge_20251106_1811'),
        ('itemmaster2', '0118_rename_salesretunitemcombo_salesreturnitemcombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnbatch',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.store'),
        ),
    ]
