# Generated by Django 5.2.5 on 2025-11-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0119_salesreturnbatch_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='return_qty',
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='return_draft_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2_deliverchallanitemcombo',
            name='return_submit_count',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
