# Generated by Django 5.0.3 on 2025-11-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0118_alter_salesorder_2_buyer_state_and_more'),
        ('itemmaster2', '0120_remove_salesorder_2_deliverchallanitemcombo_return_qty_and_more'),
    ]

    operations = [
    ]
