# Generated by Django 5.2.5 on 2025-11-07 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0120_remove_salesorder_2_deliverchallanitemcombo_return_qty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='other_income_charge',
        ),
        migrations.AlterField(
            model_name='salesorder_2_otherincomecharges',
            name='cess',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2_otherincomecharges',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2_otherincomecharges',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder_2_otherincomecharges',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturnitemcombo',
            name='item_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesreturnitemdetails'),
        ),
        migrations.CreateModel(
            name='SalesReturnOtherIncomeCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('cess', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('igst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('sgst_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cess_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SalesReturn_otherIncomeChargesOtherIncomeCharges_create', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SalesReturn_otherIncomeChargesOtherIncomeCharges_modified', to=settings.AUTH_USER_MODEL)),
                ('other_income_charges_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.otherincomecharges')),
                ('sales_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesreturn')),
            ],
        ),
    ]
