# Generated by Django 5.0.3 on 2025-11-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0121_merge_20251107_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverychallanitemdetails',
            name='return_qty',
        ),
    ]
