# Generated by Django 5.2.5 on 2025-11-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0121_remove_salesreturn_other_income_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnotherincomecharges',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_otherincomecharges'),
        ),
    ]
