# Generated by Django 5.2.5 on 2025-11-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0122_salesreturnotherincomecharges_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='sales_retun',
            new_name='sales_return',
        ),
        migrations.RenameField(
            model_name='salesorder_2_deliverychallan',
            old_name='sales_retun',
            new_name='sales_return',
        ),
    ]
