# Generated by Django 5.2.5 on 2025-11-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0122_remove_salesorder_2_deliverychallanitemdetails_return_qty'),
        ('itemmaster2', '0123_rename_sales_retun_salesinvoice_sales_return_and_more'),
    ]

    operations = [
    ]
