# Generated by Django 5.2.5 on 2025-11-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0124_merge_20251110_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='tcs_bool',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='tcs_total',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='tds_bool',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='tds_total',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='tcs_percentage',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='tcs_value',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='tds_percentage',
        ),
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='tds_value',
        ),
        migrations.AddField(
            model_name='salesreturnbatch',
            name='is_stock_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='item_detail',
            field=models.ManyToManyField(blank=True, related_name='sales_invoices', to='itemmaster2.salesinvoiceitemdetail'),
        ),
    ]
