# Generated by Django 5.2.5 on 2025-11-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0125_remove_salesreturn_tcs_bool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='item_detail',
            field=models.ManyToManyField(blank=True, to='itemmaster2.salesinvoiceitemdetail'),
        ),
    ]
