# Generated by Django 5.2.5 on 2025-11-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0188_alter_termsconditions_module'),
        ('itemmaster2', '0126_alter_salesinvoice_item_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnbatch',
            name='store',
        ),
        migrations.AddField(
            model_name='salesreturnitemcombo',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='salesreturnitemdetails',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.store'),
        ),
    ]
