# Generated by Django 5.0.3 on 2025-11-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0127_remove_salesreturnbatch_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturnitemdetails',
            name='dc_item_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dc_item_sales_return', to='itemmaster2.salesorder_2_deliverychallanitemdetails'),
        ),
    ]
