# Generated by Django 5.2.5 on 2025-11-11 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0188_alter_termsconditions_module'),
        ('itemmaster2', '0128_alter_salesreturnitemdetails_dc_item_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitemcombo',
            name='is_stock_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesreturnitemcombo',
            name='serial',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
        migrations.AddField(
            model_name='salesreturnitemdetails',
            name='is_stock_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesreturnitemdetails',
            name='serial',
            field=models.ManyToManyField(blank=True, to='itemmaster.serialnumbers'),
        ),
        migrations.CreateModel(
            name='SalesReturnBatch_combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_stock_added', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverchallanitemcombo')),
                ('item_combo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesreturnitemcombo')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnBatch_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_stock_added', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallanitemdetails')),
                ('item_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesreturnitemdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesReturnBatch',
        ),
    ]
