# Generated by Django 5.2.5 on 2025-11-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0129_salesreturnitemcombo_is_stock_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnbatch_item',
            name='item_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.salesreturnitemcombo'),
        ),
        migrations.AlterField(
            model_name='salesreturnbatch_item',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_retunbatch'),
        ),
        migrations.DeleteModel(
            name='SalesReturnBatch_combo',
        ),
    ]
