# Generated by Django 5.0.3 on 2025-11-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0130_salesreturnbatch_item_item_combo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='sales_person',
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='e_way_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
