# Generated by Django 5.0.3 on 2025-11-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0131_remove_salesreturn_sales_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='other_charges_befor_tax',
        ),
    ]
