# Generated by Django 5.0.3 on 2025-11-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0132_remove_salesreturn_other_charges_befor_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitemdetails',
            name='allowed_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
