# Generated by Django 5.0.3 on 2025-11-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0133_salesreturnitemdetails_allowed_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitemcombo',
            name='allowed_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
