# Generated by Django 5.2.5 on 2025-11-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0134_salesreturnitemcombo_allowed_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoiceitemcombo',
            name='item_combo',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitemdetail',
            name='item',
        ),
        migrations.AddField(
            model_name='salesinvoiceitemcombo',
            name='item_combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverchallanitemcombo'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitemdetail',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesorder_2_deliverychallanitemdetails'),
        ),
    ]
