# Generated by Django 5.2.5 on 2025-11-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0135_remove_salesinvoiceitemcombo_item_combo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder_2_deliverychallan',
            name='sales_invoice',
        ),
    ]
