# Generated by Django 5.2.5 on 2025-11-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0188_alter_termsconditions_module'),
        ('itemmaster2', '0136_remove_salesorder_2_deliverychallan_sales_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
