# Generated by Django 5.0.3 on 2025-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0137_salesreturn_history_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationsotherincomecharges',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='salesorder_2_otherincomecharges',
            name='currency',
        ),
        migrations.AddField(
            model_name='directsalesinvoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='quotations',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salesorder_2',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
