# Generated by Django 5.2.5 on 2025-11-18 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0188_alter_termsconditions_module'),
        ('itemmaster2', '0137_salesreturn_history_details'),
        ('userManagement', '0033_alter_allowedpermission_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rv_date', models.DateField()),
                ('emp_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('blance_emp_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cus_sup_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('against_invoice', models.BooleanField(default=False)),
                ('advance', models.BooleanField(default=False)),
                ('chq_ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('chq_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucher_bank', to='itemmaster.accountsmaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucher_created', to=settings.AUTH_USER_MODEL)),
                ('cus_sup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata')),
                ('exployee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucher_modified', to=settings.AUTH_USER_MODEL)),
                ('pay_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.paymentvoucherpayto')),
                ('pay_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucher_pay_for', to='itemmaster.accountsmaster')),
                ('pay_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.paymentvoucherpaymode')),
                ('rv_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.numberingserieslinking')),
                ('transfer_via', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.paymentvouchertransfervia')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherAdvanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_remark', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherAdvanceDetails_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherAdvanceDetails_modified', to=settings.AUTH_USER_MODEL)),
                ('receipt_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.receiptvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherAgainstInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, max_digits=15)),
                ('adjusted', models.DecimalField(decimal_places=3, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherAgainstInvoice_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherAgainstInvoice_modified', to=settings.AUTH_USER_MODEL)),
                ('receipt_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.receiptvoucher')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesinvoice')),
            ],
        ),
    ]
