# Generated by Django 5.2.5 on 2025-11-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0188_alter_termsconditions_module'),
        ('itemmaster2', '0138_receiptvoucher_receiptvoucheradvancedetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptvoucheragainstinvoice',
            name='adjusted',
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='adjusted',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.commanstatus'),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='pay_by',
            field=models.CharField(blank=True, choices=[('Supplier & Customer', 'Supplier & Customer'), ('Employee', 'Employee')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='pay_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=20, null=True),
        ),
    ]
