# Generated by Django 5.2.5 on 2025-11-18 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0188_alter_termsconditions_module'),
        ('itemmaster2', '0139_remove_receiptvoucheragainstinvoice_adjusted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='adjusted',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheragainstinvoice',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.currencyexchange'),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='receiptvoucheragainstinvoice',
            name='adjusted',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
