# Generated by Django 5.2.5 on 2025-11-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0138_remove_quotationsotherincomecharges_currency_and_more'),
        ('itemmaster2', '0140_remove_receiptvoucher_adjusted_and_more'),
    ]

    operations = [
    ]
