# Generated by Django 5.2.5 on 2025-11-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0141_merge_20251118_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptvoucher',
            old_name='exployee',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='blance_emp_amount',
        ),
    ]
