# Generated by Django 5.2.5 on 2025-11-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0190_delete_teststaantable'),
        ('itemmaster2', '0142_rename_exployee_receiptvoucher_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoucher',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
    ]
