# Generated by Django 5.2.5 on 2025-11-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0143_receiptvoucher_history_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptvoucheragainstinvoice',
            name='balance',
        ),
    ]
