# Generated by Django 5.2.5 on 2025-11-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0144_remove_receiptvoucheragainstinvoice_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='transfer_via',
        ),
    ]
