# Generated by Django 5.2.5 on 2025-11-24 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0192_alter_numberingseries_resource'),
        ('itemmaster2', '0147_creditnote_creditnoteaccount_creditnoteitemdetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnoteotherincomecharges',
            old_name='other_income_charges_id',
            new_name='other_income_charges',
        ),
        migrations.AddField(
            model_name='creditnoteitemdetails',
            name='tcs_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditnoteitemdetails',
            name='tds_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='creditnoteotherincomecharges',
            name='hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.hsn'),
        ),
    ]
