# Generated by Django 5.2.5 on 2025-11-26 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0192_alter_numberingseries_resource'),
        ('itemmaster2', '0148_rename_other_income_charges_id_creditnoteotherincomecharges_other_income_charges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitemdetails',
            name='allowed_qty',
        ),
        migrations.CreateModel(
            name='CreditNoteComboItemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('display', models.CharField(blank=True, max_length=50, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_credit_note_combo_item_details', to=settings.AUTH_USER_MODEL)),
                ('credit_note_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.creditnoteitemdetails')),
                ('itemmaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.itemmaster')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_credit_note_combo_item_details', to=settings.AUTH_USER_MODEL)),
                ('sales_return_combo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesreturnitemcombo')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.uom')),
            ],
        ),
    ]
