# Generated by Django 5.0.3 on 2025-11-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0149_remove_salesreturnitemdetails_allowed_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnotecomboitemdetails',
            name='sales_return_combo_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster2.salesreturnitemcombo'),
        ),
    ]
