# Generated by Django 5.2.5 on 2025-11-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0149_remove_salesreturnitemdetails_allowed_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
    ]
