# Generated by Django 5.0.3 on 2025-11-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0150_alter_creditnotecomboitemdetails_sales_return_combo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnoteaccount',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.creditnote'),
        ),
        migrations.AlterField(
            model_name='creditnoteitemdetails',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.creditnote'),
        ),
        migrations.AlterField(
            model_name='creditnoteotherincomecharges',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.creditnote'),
        ),
    ]
