# Generated by Django 5.2.5 on 2025-11-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0150_salesreturn_is_account_general_ledger_upated'),
        ('itemmaster2', '0151_alter_creditnoteaccount_credit_note_and_more'),
    ]

    operations = [
    ]
