# Generated by Django 5.2.5 on 2025-11-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0152_merge_20251128_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receiptvoucheradvancedetails',
            name='receipt_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucher'),
        ),
        migrations.AlterField(
            model_name='receiptvoucheragainstinvoice',
            name='receipt_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucher'),
        ),
    ]
