# Generated by Django 5.2.5 on 2025-12-02 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0197_accountsgeneralledger_credit_note_voucher_no'),
        ('itemmaster2', '0153_creditnote_is_account_general_ledger_upated_and_more'),
        ('userManagement', '0040_alter_paymentvoucheragainstinvoice_payment_voucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='cus_sup',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='cus_sup_amount',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='emp_amount',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='receiptvoucher',
            name='pay_for',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheradvancedetails',
            name='receipt_voucher',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheragainstinvoice',
            name='receipt_voucher',
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReceiptVoucherAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherAccount_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherAccount_modified', to=settings.AUTH_USER_MODEL)),
                ('receipt_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherEmployee_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherEmployee_modified', to=settings.AUTH_USER_MODEL)),
                ('pay_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherEmployee_pay_for', to='itemmaster.accountsmaster')),
                ('receipt_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucher')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptVoucherSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_sup_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherSupplier_created', to=settings.AUTH_USER_MODEL)),
                ('cus_sup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherSupplier_modified', to=settings.AUTH_USER_MODEL)),
                ('receipt_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucher')),
            ],
        ),
        migrations.AddField(
            model_name='receiptvoucheradvancedetails',
            name='receipt_voucher_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvouchersupplier'),
        ),
        migrations.AddField(
            model_name='receiptvoucheragainstinvoice',
            name='receipt_voucher_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvouchersupplier'),
        ),
    ]
