# Generated by Django 5.2.5 on 2025-12-03 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0197_accountsgeneralledger_credit_note_voucher_no'),
        ('itemmaster2', '0154_remove_receiptvoucher_cus_sup_and_more'),
        ('userManagement', '0040_alter_paymentvoucheragainstinvoice_payment_voucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptvoucheremployee',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheremployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheremployee',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheremployee',
            name='pay_for',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheremployee',
            name='receipt_voucher',
        ),
        migrations.RemoveField(
            model_name='receiptvouchersupplier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='receiptvouchersupplier',
            name='cus_sup',
        ),
        migrations.RemoveField(
            model_name='receiptvouchersupplier',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='receiptvouchersupplier',
            name='receipt_voucher',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheragainstinvoice',
            name='receipt_voucher_supplier',
        ),
        migrations.RemoveField(
            model_name='receiptvoucheradvancedetails',
            name='receipt_voucher_supplier',
        ),
        migrations.AlterField(
            model_name='receiptvoucher',
            name='pay_by',
            field=models.CharField(blank=True, choices=[('Account', 'Account'), ('Supplier & Customer', 'Supplier & Customer'), ('Employee', 'Employee')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ReceiptVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherAccount_created', to=settings.AUTH_USER_MODEL)),
                ('cus_sup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherAccount_modified', to=settings.AUTH_USER_MODEL)),
                ('pay_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherEmployee_pay_for', to='itemmaster.accountsmaster')),
                ('receipt_voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucher')),
            ],
        ),
        migrations.AddField(
            model_name='receiptvoucheradvancedetails',
            name='receipt_voucher_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucherline'),
        ),
        migrations.AddField(
            model_name='receiptvoucheragainstinvoice',
            name='receipt_voucher_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucherline'),
        ),
        migrations.DeleteModel(
            name='ReceiptVoucherAccount',
        ),
        migrations.DeleteModel(
            name='ReceiptVoucherEmployee',
        ),
        migrations.DeleteModel(
            name='ReceiptVoucherSupplier',
        ),
    ]
