# Generated by Django 5.2.5 on 2025-12-04 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0156_salespaiddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespaiddetails',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='receiptvoucherline',
            name='receipt_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster2.receiptvoucher'),
        ),
    ]
