# Generated by Django 5.2.5 on 2025-12-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0197_accountsgeneralledger_credit_note_voucher_no'),
        ('itemmaster2', '0157_remove_salespaiddetails_modified_by_and_more'),
        ('userManagement', '0040_alter_paymentvoucheragainstinvoice_payment_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptvoucherline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.accountsmaster'),
        ),
        migrations.AlterField(
            model_name='receiptvoucherline',
            name='cus_sup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.supplierformdata'),
        ),
        migrations.AlterField(
            model_name='receiptvoucherline',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='userManagement.employee'),
        ),
    ]
