# Generated by Django 5.2.5 on 2025-12-04 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster', '0197_accountsgeneralledger_credit_note_voucher_no'),
        ('itemmaster2', '0158_alter_receiptvoucherline_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptvoucherline',
            name='pay_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ReceiptVoucherEmployee_pay_for', to='itemmaster.accountsmaster'),
        ),
    ]
