# Generated by Django 5.2.5 on 2025-12-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0159_alter_receiptvoucherline_pay_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptvoucher',
            name='is_account_general_ledger_upated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptvoucher',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
