# Generated by Django 5.2.5 on 2025-12-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmaster2', '0160_receiptvoucher_is_account_general_ledger_upated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptvoucher',
            old_name='is_account_general_ledger_upated',
            new_name='is_account_general_ledger_updated',
        ),
    ]
