# Generated by Django 5.1.1 on 2025-03-17 07:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiryDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?9?1?\\s?-?\\d{1,}-?\\s?\\d{1,}')])),
                ('status', models.CharField(choices=[('NOT_CONTACTED', 'NOT_CONTACTED'), ('CONVERTED_TO_LEAD', 'CONVERTED_TO_LEAD'), ('JUNK', 'JUNK'), ('IN_PROGRESS', 'IN_PROGRESS')], max_length=50)),
                ('mobile_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91-1234567890' or '091 1234 567890'. Up to 15 digits allowed.", regex='^\\+?9?1?\\s?-?\\d{1,}-?\\s?\\d{1,}')])),
                ('other_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91-1234567890' or '091 1234 567890'. Up to 15 digits allowed.", regex='^\\+?9?1?\\s?-?\\d{1,}-?\\s?\\d{1,}')])),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('counter', models.CharField(blank=True, max_length=50, null=True)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('whatsapps_template', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sales_person', models.BooleanField(default=False)),
                ('is_admin_person', models.BooleanField(default=False)),
                ('is_enquiry_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conferencedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_in_charges', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_Conferencedata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
