# Generated by Django 5.1.1 on 2025-03-17 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EnquriFromapi', '0001_initial'),
        ('itemmaster', '0001_initial'),
        ('itemmaster2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencedata',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.currencyexchange'),
        ),
        migrations.AddField(
            model_name='conferencedata',
            name='default_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itemmaster.store'),
        ),
        migrations.AddField(
            model_name='conferencedata',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='conferencedata',
            name='in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferencedata',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_Conferencedata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='activity',
            field=models.ManyToManyField(blank=True, to='itemmaster2.activites'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='conference_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnquriFromapi.conferencedata'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_Enquiry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.districts'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='email_record',
            field=models.ManyToManyField(blank=True, to='itemmaster2.emailrecord'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='history_details',
            field=models.ManyToManyField(blank=True, to='itemmaster.itemmasterhistory'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='link_contact_detalis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='itemmaster.contactdetalis'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_Enquiry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='note',
            field=models.ManyToManyField(blank=True, to='itemmaster2.notes'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.pincode'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemmaster.states'),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='interests',
            field=models.ManyToManyField(blank=True, to='EnquriFromapi.product'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
