# Generated by Django 5.1.1 on 2025-03-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydatas',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='over_due',
            field=models.BooleanField(default=False),
        ),
    ]
