# Generated by Django 5.1.3 on 2025-03-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0003_enquirydatas_last_activity_enquirydatas_over_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydatas',
            name='activity_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
