# Generated by Django 5.1.3 on 2025-04-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0004_enquirydatas_activity_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirydatas',
            name='activity_count',
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='call_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='meeting_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enquirydatas',
            name='task_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
