# Generated by Django 5.1.3 on 2025-04-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0005_remove_enquirydatas_activity_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquirydatas',
            name='mail_count',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
