# Generated by Django 5.0.3 on 2025-09-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnquriFromapi', '0006_enquirydatas_mail_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirydatas',
            name='status',
            field=models.CharField(choices=[('Not Contacted', 'Not Contacted'), ('Converted To Lead', 'Converted To Lead'), ('Junk', 'Junk'), ('Inprogress', 'Inprogress')], max_length=50),
        ),
    ]
